<?xml version="1.0" encoding="utf-8"?>
<CaR version="20150810">
<Macro Name="Poincare Geometry/01: Point (13)">
<Parameter name="k">=k</Parameter>
<Parameter name="P2">P2</Parameter>
<Comment>
<P>Create a point on k.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<PointOn name="P2" n="2" mainparameter="true" on="k" inside="true" x="1.2166064617758128" y="3.4297394493749858" shape="circle">Point on k</PointOn>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/02: Line (27)">
<Parameter name="k">=k</Parameter>
<Parameter name="P10">A</Parameter>
<Parameter name="P11">B</Parameter>
<Comment>
<P>Line through two points.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P10" n="2" mainparameter="true" x="-3.252120352517492" y="1.2955556910592485">Point at -3.25212, 1.29556</Point>
<Point name="P11" n="3" mainparameter="true" x="1.709668925682638" y="2.295606243254625">Point at 1.70967, 2.29561</Point>
<Line name="g1" n="4" color="1" hidden="super" from="P1" to="P10">Gerade durch P1 und P10</Line>
<Midpoint name="M1" n="5" color="1" hidden="super" first="P1" second="P10">Mitte zwischen P1 und P10</Midpoint>
<Plumb name="l1" n="6" color="1" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="7" color="1" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="8" color="1" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="9" color="1" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="10" color="1" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="11" color="1" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="12" color="1" hidden="super" from="P10" to="P11">Gerade durch P10 und P11</Line>
<Midpoint name="M3" n="13" color="1" hidden="super" first="P10" second="P11">Mitte zwischen P10 und P11</Midpoint>
<Plumb name="l3" n="14" color="1" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="15" color="1" hidden="super" from="P10" to="S2">Gerade durch P10 und S2</Line>
<Midpoint name="M4" n="16" color="1" hidden="super" first="P10" second="S2">Mitte zwischen P10 und S2</Midpoint>
<Plumb name="l4" n="17" color="1" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="18" color="1" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Circle name="k2" n="19" color="1" target="true" through="P10" midpoint="S3" acute="true">Kreis um S3 durch P10</Circle>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/03: Limited Line (27)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="P2">A</Parameter>
<Parameter name="P3">B</Parameter>
<Comment>
<P>Line through A and B. Only the part of the line in the
basic circle is shown.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P2" n="2" mainparameter="true" x="-4.307444354036484" y="-0.30075007284748445">Point at -4.30744, -0.30075</Point>
<Point name="P3" n="3" mainparameter="true" x="3.0368" y="4.18466">Point at 3.0368, 4.18466</Point>
<Line name="g1" n="4" hidden="super" from="P1" to="P2">Gerade durch P1 und P2</Line>
<Midpoint name="M1" n="5" hidden="super" first="P1" second="P2">Mitte zwischen P1 und P2</Midpoint>
<Plumb name="l1" n="6" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="7" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="8" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="9" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="10" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="11" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="12" hidden="super" from="P2" to="P3">Gerade durch P2 und P3</Line>
<Midpoint name="M3" n="13" hidden="super" first="P2" second="P3">Mitte zwischen P2 und P3</Midpoint>
<Plumb name="l3" n="14" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="15" hidden="super" from="P2" to="S2">Gerade durch P2 und S2</Line>
<Midpoint name="M4" n="16" hidden="super" first="P2" second="S2">Mitte zwischen P2 und S2</Midpoint>
<Plumb name="l4" n="17" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="18" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Circle name="k2" n="19" target="true" through="P2" midpoint="S3" start="S4" end="S5" acute="true">Kreis um S3 durch P2</Circle>
<Intersection name="S4" n="20" hidden="true" target="true" first="k" second="k2" which="second">Schnitt zwischen k und k2</Intersection>
<Intersection name="S5" n="21" hidden="true" target="true" first="k2" second="k" which="second">Schnitt zwischen k2 und k</Intersection>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/04: Line segment (32)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="P14">A</Parameter>
<Parameter name="P15">B</Parameter>
<Comment>
<P>Line segment from A to B.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P14" n="2" mainparameter="true" x="1.5375625214899449" y="4.011257107619612">Point at 1.53756, 4.01126</Point>
<Point name="P15" n="3" mainparameter="true" x="-3.4507214046766252" y="-1.4005603594478917">Point at -3.45072, -1.40056</Point>
<Line name="g1" n="4" hidden="super" from="P1" to="P15">Gerade durch P1 und P15</Line>
<Midpoint name="M1" n="5" hidden="super" first="P1" second="P15">Mitte zwischen P1 und P15</Midpoint>
<Plumb name="l1" n="6" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="7" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="8" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="9" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="10" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="11" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="12" hidden="super" from="P15" to="P14">Gerade durch P15 und P14</Line>
<Midpoint name="M3" n="13" hidden="super" first="P15" second="P14">Mitte zwischen P15 und P14</Midpoint>
<Plumb name="l3" n="14" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="15" hidden="super" from="P15" to="S2">Gerade durch P15 und S2</Line>
<Midpoint name="M4" n="16" hidden="super" first="P15" second="S2">Mitte zwischen P15 und S2</Midpoint>
<Plumb name="l4" n="17" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="18" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Circle name="k2" n="19" target="true" through="P15" midpoint="S3" start="P15" end="P14" acute="true">Kreis um S3 durch P15</Circle>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/05: Circle (19)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="P16">M</Parameter>
<Parameter name="P17">A</Parameter>
<Comment>
<P>Circle around M through A.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P16" n="2" mainparameter="true" x="1.2081475452336594" y="1.7053522738256321">Point at 1.20815, 1.70535</Point>
<Point name="P17" n="3" mainparameter="true" x="2.855222426515075" y="3.6112532078798423">Point at 2.85522, 3.61125</Point>
<Line name="g1" n="4" hidden="super" from="P1" to="P16">Gerade durch P1 und P16</Line>
<Midpoint name="M1" n="5" hidden="super" first="P1" second="P16">Mitte zwischen P1 und P16</Midpoint>
<Plumb name="l1" n="6" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="7" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="8" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="9" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="10" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="11" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="12" hidden="super" from="P16" to="P17">Gerade durch P16 und P17</Line>
<Midpoint name="M3" n="13" hidden="super" first="P16" second="P17">Mitte zwischen P16 und P17</Midpoint>
<Plumb name="l3" n="14" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="15" hidden="super" from="P16" to="S2">Gerade durch P16 und S2</Line>
<Midpoint name="M4" n="16" hidden="super" first="P16" second="S2">Mitte zwischen P16 und S2</Midpoint>
<Plumb name="l4" n="17" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="18" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Line name="g5" n="19" hidden="super" from="S3" to="P17">Gerade durch S3 und P17</Line>
<Plumb name="l5" n="20" hidden="super" point="P17" line="g5" valid="true">Lot durch P17 zu g5</Plumb>
<Line name="g6" n="21" hidden="super" from="P1" to="P16">Gerade durch P1 und P16</Line>
<Intersection name="S4" n="22" hidden="super" first="l5" second="g6">Schnitt zwischen l5 und g6</Intersection>
<Circle name="k2" n="23" target="true" through="P17" midpoint="S4" acute="true">Kreis um S4 durch P17</Circle>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/06: Circle with radius AB (20)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="P24">A</Parameter>
<Parameter name="P25">B</Parameter>
<Parameter name="P26">M</Parameter>
<Comment>
<P>Circle around M with radius AB.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P24" n="2" mainparameter="true" x="-0.8859905181098517" y="0.9994630389907408">Point at -0.88599, 0.99946</Point>
<Point name="P25" n="3" mainparameter="true" x="-1.474231547138928" y="3.493605002074024">Point at -1.47423, 3.49361</Point>
<Point name="P26" n="4" mainparameter="true" x="3.5375820201888057" y="0.7641666273791102">Point at 3.53758, 0.76417</Point>
<Line name="g1" n="5" hidden="super" from="P1" to="P24">Gerade durch P1 und P24</Line>
<Midpoint name="M1" n="6" hidden="super" first="P1" second="P24">Mitte zwischen P1 und P24</Midpoint>
<Plumb name="l1" n="7" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="8" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="9" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="10" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="11" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="12" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="13" hidden="super" from="P24" to="P26">Gerade durch P24 und P26</Line>
<Midpoint name="M3" n="14" hidden="super" first="P24" second="P26">Mitte zwischen P24 und P26</Midpoint>
<Plumb name="l3" n="15" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="16" hidden="super" from="P24" to="S2">Gerade durch P24 und S2</Line>
<Midpoint name="M4" n="17" hidden="super" first="P24" second="S2">Mitte zwischen P24 und S2</Midpoint>
<Plumb name="l4" n="18" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="19" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Circle name="k2" n="20" hidden="super" through="P24" midpoint="S3" acute="true">Kreis um S3 durch P24</Circle>
<Line name="g5" n="21" hidden="super" from="P1" to="S3">Gerade durch P1 und S3</Line>
<Intersection name="S4" n="22" hidden="super" first="g5" second="k2" closeto="P1" which="second">Schnitt zwischen g5 und k2</Intersection>
<Line name="g6" n="23" hidden="super" from="P1" to="P24">Gerade durch P1 und P24</Line>
<Midpoint name="M5" n="24" hidden="super" first="P1" second="P24">Mitte zwischen P1 und P24</Midpoint>
<Plumb name="l5" n="25" hidden="super" point="M5" line="g6" valid="true">Lot durch M5 zu g6</Plumb>
<Intersection name="S5" n="26" hidden="super" first="l5" second="k" which="second">Schnitt zwischen l5 und k</Intersection>
<Line name="g7" n="27" hidden="super" from="P1" to="S5">Gerade durch P1 und S5</Line>
<Midpoint name="M6" n="28" hidden="super" first="P1" second="S5">Mitte zwischen P1 und S5</Midpoint>
<Plumb name="l6" n="29" hidden="super" point="M6" line="g7" valid="true">Lot durch M6 zu g7</Plumb>
<Intersection name="S6" n="30" hidden="super" first="g6" second="l6">Schnitt zwischen g6 und l6</Intersection>
<Line name="g8" n="31" hidden="super" from="P24" to="S4">Gerade durch P24 und S4</Line>
<Midpoint name="M7" n="32" hidden="super" first="P24" second="S4">Mitte zwischen P24 und S4</Midpoint>
<Plumb name="l7" n="33" hidden="super" point="M7" line="g8" valid="true">Lot durch M7 zu g8</Plumb>
<Line name="g9" n="34" hidden="super" from="P24" to="S6">Gerade durch P24 und S6</Line>
<Midpoint name="M8" n="35" hidden="super" first="P24" second="S6">Mitte zwischen P24 und S6</Midpoint>
<Plumb name="l8" n="36" hidden="super" point="M8" line="g9" valid="true">Lot durch M8 zu g9</Plumb>
<Intersection name="S7" n="37" hidden="super" first="l7" second="l8">Schnitt zwischen l7 und l8</Intersection>
<Line name="g10" n="38" hidden="super" from="S7" to="S4">Gerade durch S7 und S4</Line>
<Plumb name="l9" n="39" hidden="super" point="S4" line="g10" valid="true">Lot durch S4 zu g10</Plumb>
<Line name="g11" n="40" hidden="super" from="P1" to="P24">Gerade durch P1 und P24</Line>
<Intersection name="S8" n="41" hidden="super" first="l9" second="g11">Schnitt zwischen l9 und g11</Intersection>
<Circle name="k3" n="42" hidden="super" through="S4" midpoint="S8" acute="true">Kreis um S8 durch S4</Circle>
<Intersection name="S9" n="43" hidden="super" first="k2" second="k3" which="first">Schnitt zwischen k2 und k3</Intersection>
<Intersection name="S10" n="44" hidden="super" first="k2" second="k3" which="second">Schnitt zwischen k2 und k3</Intersection>
<Line name="g12" n="45" hidden="super" from="P1" to="S10">Gerade durch P1 und S10</Line>
<Midpoint name="M9" n="46" hidden="super" first="P1" second="S10">Mitte zwischen P1 und S10</Midpoint>
<Plumb name="l10" n="47" hidden="super" point="M9" line="g12" valid="true">Lot durch M9 zu g12</Plumb>
<Intersection name="S11" n="48" hidden="super" first="l10" second="k" which="second">Schnitt zwischen l10 und k</Intersection>
<Line name="g13" n="49" hidden="super" from="P1" to="S11">Gerade durch P1 und S11</Line>
<Midpoint name="M10" n="50" hidden="super" first="P1" second="S11">Mitte zwischen P1 und S11</Midpoint>
<Plumb name="l11" n="51" hidden="super" point="M10" line="g13" valid="true">Lot durch M10 zu g13</Plumb>
<Intersection name="S12" n="52" hidden="super" first="g12" second="l11">Schnitt zwischen g12 und l11</Intersection>
<Line name="g14" n="53" hidden="super" from="S10" to="S9">Gerade durch S10 und S9</Line>
<Midpoint name="M11" n="54" hidden="super" first="S10" second="S9">Mitte zwischen S10 und S9</Midpoint>
<Plumb name="l12" n="55" hidden="super" point="M11" line="g14" valid="true">Lot durch M11 zu g14</Plumb>
<Line name="g15" n="56" hidden="super" from="S10" to="S12">Gerade durch S10 und S12</Line>
<Midpoint name="M12" n="57" hidden="super" first="S10" second="S12">Mitte zwischen S10 und S12</Midpoint>
<Plumb name="l13" n="58" hidden="super" point="M12" line="g15" valid="true">Lot durch M12 zu g15</Plumb>
<Intersection name="S13" n="59" hidden="super" first="l12" second="l13">Schnitt zwischen l12 und l13</Intersection>
<Line name="g16" n="60" hidden="super" from="S13" to="S9">Gerade durch S13 und S9</Line>
<Plumb name="l14" n="61" hidden="super" point="S9" line="g16" valid="true">Lot durch S9 zu g16</Plumb>
<Line name="g17" n="62" hidden="super" from="P1" to="S10">Gerade durch P1 und S10</Line>
<Intersection name="S14" n="63" hidden="super" first="l14" second="g17">Schnitt zwischen l14 und g17</Intersection>
<Circle name="k4" n="64" hidden="super" through="S9" midpoint="S14" acute="true">Kreis um S14 durch S9</Circle>
<Line name="g18" n="65" hidden="super" from="P1" to="S9">Gerade durch P1 und S9</Line>
<Midpoint name="M13" n="66" hidden="super" first="P1" second="S9">Mitte zwischen P1 und S9</Midpoint>
<Plumb name="l15" n="67" hidden="super" point="M13" line="g18" valid="true">Lot durch M13 zu g18</Plumb>
<Intersection name="S15" n="68" hidden="super" first="l15" second="k" which="second">Schnitt zwischen l15 und k</Intersection>
<Line name="g19" n="69" hidden="super" from="P1" to="S15">Gerade durch P1 und S15</Line>
<Midpoint name="M14" n="70" hidden="super" first="P1" second="S15">Mitte zwischen P1 und S15</Midpoint>
<Plumb name="l16" n="71" hidden="super" point="M14" line="g19" valid="true">Lot durch M14 zu g19</Plumb>
<Intersection name="S16" n="72" hidden="super" first="g18" second="l16">Schnitt zwischen g18 und l16</Intersection>
<Line name="g20" n="73" hidden="super" from="S9" to="S10">Gerade durch S9 und S10</Line>
<Midpoint name="M15" n="74" hidden="super" first="S9" second="S10">Mitte zwischen S9 und S10</Midpoint>
<Plumb name="l17" n="75" hidden="super" point="M15" line="g20" valid="true">Lot durch M15 zu g20</Plumb>
<Line name="g21" n="76" hidden="super" from="S9" to="S16">Gerade durch S9 und S16</Line>
<Midpoint name="M16" n="77" hidden="super" first="S9" second="S16">Mitte zwischen S9 und S16</Midpoint>
<Plumb name="l18" n="78" hidden="super" point="M16" line="g21" valid="true">Lot durch M16 zu g21</Plumb>
<Intersection name="S17" n="79" hidden="super" first="l17" second="l18">Schnitt zwischen l17 und l18</Intersection>
<Line name="g22" n="80" hidden="super" from="S17" to="S10">Gerade durch S17 und S10</Line>
<Plumb name="l19" n="81" hidden="super" point="S10" line="g22" valid="true">Lot durch S10 zu g22</Plumb>
<Line name="g23" n="82" hidden="super" from="P1" to="S9">Gerade durch P1 und S9</Line>
<Intersection name="S18" n="83" hidden="super" first="l19" second="g23">Schnitt zwischen l19 und g23</Intersection>
<Circle name="k5" n="84" hidden="super" through="S10" midpoint="S18" acute="true">Kreis um S18 durch S10</Circle>
<Intersection name="S19" n="85" hidden="super" first="k4" second="k5" which="first">Schnitt zwischen k4 und k5</Intersection>
<Intersection name="S20" n="86" hidden="super" first="k4" second="k5" which="second">Schnitt zwischen k4 und k5</Intersection>
<Line name="g24" n="87" hidden="super" from="P1" to="S20">Gerade durch P1 und S20</Line>
<Midpoint name="M17" n="88" hidden="super" first="P1" second="S20">Mitte zwischen P1 und S20</Midpoint>
<Plumb name="l20" n="89" hidden="super" point="M17" line="g24" valid="true">Lot durch M17 zu g24</Plumb>
<Intersection name="S21" n="90" hidden="super" first="l20" second="k" which="second">Schnitt zwischen l20 und k</Intersection>
<Line name="g25" n="91" hidden="super" from="P1" to="S21">Gerade durch P1 und S21</Line>
<Midpoint name="M18" n="92" hidden="super" first="P1" second="S21">Mitte zwischen P1 und S21</Midpoint>
<Plumb name="l21" n="93" hidden="super" point="M18" line="g25" valid="true">Lot durch M18 zu g25</Plumb>
<Intersection name="S22" n="94" hidden="super" first="g24" second="l21">Schnitt zwischen g24 und l21</Intersection>
<Line name="g26" n="95" hidden="super" from="S20" to="S19">Gerade durch S20 und S19</Line>
<Midpoint name="M19" n="96" hidden="super" first="S20" second="S19">Mitte zwischen S20 und S19</Midpoint>
<Plumb name="l22" n="97" hidden="super" point="M19" line="g26" valid="true">Lot durch M19 zu g26</Plumb>
<Line name="g27" n="98" hidden="super" from="S20" to="S22">Gerade durch S20 und S22</Line>
<Midpoint name="M20" n="99" hidden="super" first="S20" second="S22">Mitte zwischen S20 und S22</Midpoint>
<Plumb name="l23" n="100" hidden="super" point="M20" line="g27" valid="true">Lot durch M20 zu g27</Plumb>
<Intersection name="S23" n="101" hidden="super" first="l22" second="l23">Schnitt zwischen l22 und l23</Intersection>
<Circle name="k6" n="102" hidden="super" through="S20" midpoint="S23" acute="true">Kreis um S23 durch S20</Circle>
<Line name="g28" n="103" hidden="super" from="P1" to="P24">Gerade durch P1 und P24</Line>
<Midpoint name="M21" n="104" hidden="super" first="P1" second="P24">Mitte zwischen P1 und P24</Midpoint>
<Plumb name="l24" n="105" hidden="super" point="M21" line="g28" valid="true">Lot durch M21 zu g28</Plumb>
<Intersection name="S24" n="106" hidden="super" first="l24" second="k" which="second">Schnitt zwischen l24 und k</Intersection>
<Line name="g29" n="107" hidden="super" from="P1" to="S24">Gerade durch P1 und S24</Line>
<Midpoint name="M22" n="108" hidden="super" first="P1" second="S24">Mitte zwischen P1 und S24</Midpoint>
<Plumb name="l25" n="109" hidden="super" point="M22" line="g29" valid="true">Lot durch M22 zu g29</Plumb>
<Intersection name="S25" n="110" hidden="super" first="g28" second="l25">Schnitt zwischen g28 und l25</Intersection>
<Line name="g30" n="111" hidden="super" from="P24" to="P25">Gerade durch P24 und P25</Line>
<Midpoint name="M23" n="112" hidden="super" first="P24" second="P25">Mitte zwischen P24 und P25</Midpoint>
<Plumb name="l26" n="113" hidden="super" point="M23" line="g30" valid="true">Lot durch M23 zu g30</Plumb>
<Line name="g31" n="114" hidden="super" from="P24" to="S25">Gerade durch P24 und S25</Line>
<Midpoint name="M24" n="115" hidden="super" first="P24" second="S25">Mitte zwischen P24 und S25</Midpoint>
<Plumb name="l27" n="116" hidden="super" point="M24" line="g31" valid="true">Lot durch M24 zu g31</Plumb>
<Intersection name="S26" n="117" hidden="super" first="l26" second="l27">Schnitt zwischen l26 und l27</Intersection>
<Line name="g32" n="118" hidden="super" from="S26" to="P25">Gerade durch S26 und P25</Line>
<Plumb name="l28" n="119" hidden="super" point="P25" line="g32" valid="true">Lot durch P25 zu g32</Plumb>
<Line name="g33" n="120" hidden="super" from="P1" to="P24">Gerade durch P1 und P24</Line>
<Intersection name="S27" n="121" hidden="super" first="l28" second="g33">Schnitt zwischen l28 und g33</Intersection>
<Circle name="k7" n="122" hidden="super" through="P25" midpoint="S27" acute="true">Kreis um S27 durch P25</Circle>
<Intersection name="S28" n="123" hidden="super" first="k7" second="k6" which="second">Schnitt zwischen k7 und k6</Intersection>
<Intersection name="S29" n="124" hidden="super" first="k" second="k2" which="first">Schnitt zwischen k und k2</Intersection>
<Intersection name="S30" n="125" hidden="super" first="k" second="k2" which="second">Schnitt zwischen k und k2</Intersection>
<Line name="g34" n="126" hidden="super" from="S30" to="S29">Gerade durch S30 und S29</Line>
<Midpoint name="M25" n="127" hidden="super" first="S30" second="S29">Mitte zwischen S30 und S29</Midpoint>
<Plumb name="l29" n="128" hidden="super" point="M25" line="g34" valid="true">Lot durch M25 zu g34</Plumb>
<Line name="g35" n="129" hidden="super" from="S30" to="S28">Gerade durch S30 und S28</Line>
<Midpoint name="M26" n="130" hidden="super" first="S30" second="S28">Mitte zwischen S30 und S28</Midpoint>
<Plumb name="l30" n="131" hidden="super" point="M26" line="g35" valid="true">Lot durch M26 zu g35</Plumb>
<Intersection name="S31" n="132" hidden="super" first="l29" second="l30">Schnitt zwischen l29 und l30</Intersection>
<Circle name="k8" n="133" hidden="super" through="S30" midpoint="S31" acute="true">Kreis um S31 durch S30</Circle>
<Line name="g36" n="134" hidden="super" from="P1" to="S3">Gerade durch P1 und S3</Line>
<Intersection name="S32" n="135" hidden="super" first="g36" second="k2" closeto="P1" which="second">Schnitt zwischen g36 und k2</Intersection>
<Line name="g37" n="136" hidden="super" from="P1" to="P26">Gerade durch P1 und P26</Line>
<Midpoint name="M27" n="137" hidden="super" first="P1" second="P26">Mitte zwischen P1 und P26</Midpoint>
<Plumb name="l31" n="138" hidden="super" point="M27" line="g37" valid="true">Lot durch M27 zu g37</Plumb>
<Intersection name="S33" n="139" hidden="super" first="l31" second="k" which="second">Schnitt zwischen l31 und k</Intersection>
<Line name="g38" n="140" hidden="super" from="P1" to="S33">Gerade durch P1 und S33</Line>
<Midpoint name="M28" n="141" hidden="super" first="P1" second="S33">Mitte zwischen P1 und S33</Midpoint>
<Plumb name="l32" n="142" hidden="super" point="M28" line="g38" valid="true">Lot durch M28 zu g38</Plumb>
<Intersection name="S34" n="143" hidden="super" first="g37" second="l32">Schnitt zwischen g37 und l32</Intersection>
<Line name="g39" n="144" hidden="super" from="P26" to="S32">Gerade durch P26 und S32</Line>
<Midpoint name="M29" n="145" hidden="super" first="P26" second="S32">Mitte zwischen P26 und S32</Midpoint>
<Plumb name="l33" n="146" hidden="super" point="M29" line="g39" valid="true">Lot durch M29 zu g39</Plumb>
<Line name="g40" n="147" hidden="super" from="P26" to="S34">Gerade durch P26 und S34</Line>
<Midpoint name="M30" n="148" hidden="super" first="P26" second="S34">Mitte zwischen P26 und S34</Midpoint>
<Plumb name="l34" n="149" hidden="super" point="M30" line="g40" valid="true">Lot durch M30 zu g40</Plumb>
<Intersection name="S35" n="150" hidden="super" first="l33" second="l34">Schnitt zwischen l33 und l34</Intersection>
<Line name="g41" n="151" hidden="super" from="S35" to="S32">Gerade durch S35 und S32</Line>
<Plumb name="l35" n="152" hidden="super" point="S32" line="g41" valid="true">Lot durch S32 zu g41</Plumb>
<Line name="g42" n="153" hidden="super" from="P1" to="P26">Gerade durch P1 und P26</Line>
<Intersection name="S36" n="154" hidden="super" first="l35" second="g42">Schnitt zwischen l35 und g42</Intersection>
<Circle name="k9" n="155" hidden="super" through="S32" midpoint="S36" acute="true">Kreis um S36 durch S32</Circle>
<Intersection name="S37" n="156" hidden="super" first="k2" second="k9" which="first">Schnitt zwischen k2 und k9</Intersection>
<Intersection name="S38" n="157" hidden="super" first="k2" second="k9" which="second">Schnitt zwischen k2 und k9</Intersection>
<Line name="g43" n="158" hidden="super" from="P1" to="S38">Gerade durch P1 und S38</Line>
<Midpoint name="M31" n="159" hidden="super" first="P1" second="S38">Mitte zwischen P1 und S38</Midpoint>
<Plumb name="l36" n="160" hidden="super" point="M31" line="g43" valid="true">Lot durch M31 zu g43</Plumb>
<Intersection name="S39" n="161" hidden="super" first="l36" second="k" which="second">Schnitt zwischen l36 und k</Intersection>
<Line name="g44" n="162" hidden="super" from="P1" to="S39">Gerade durch P1 und S39</Line>
<Midpoint name="M32" n="163" hidden="super" first="P1" second="S39">Mitte zwischen P1 und S39</Midpoint>
<Plumb name="l37" n="164" hidden="super" point="M32" line="g44" valid="true">Lot durch M32 zu g44</Plumb>
<Intersection name="S40" n="165" hidden="super" first="g43" second="l37">Schnitt zwischen g43 und l37</Intersection>
<Line name="g45" n="166" hidden="super" from="S38" to="S37">Gerade durch S38 und S37</Line>
<Midpoint name="M33" n="167" hidden="super" first="S38" second="S37">Mitte zwischen S38 und S37</Midpoint>
<Plumb name="l38" n="168" hidden="super" point="M33" line="g45" valid="true">Lot durch M33 zu g45</Plumb>
<Line name="g46" n="169" hidden="super" from="S38" to="S40">Gerade durch S38 und S40</Line>
<Midpoint name="M34" n="170" hidden="super" first="S38" second="S40">Mitte zwischen S38 und S40</Midpoint>
<Plumb name="l39" n="171" hidden="super" point="M34" line="g46" valid="true">Lot durch M34 zu g46</Plumb>
<Intersection name="S41" n="172" hidden="super" first="l38" second="l39">Schnitt zwischen l38 und l39</Intersection>
<Line name="g47" n="173" hidden="super" from="S41" to="S37">Gerade durch S41 und S37</Line>
<Plumb name="l40" n="174" hidden="super" point="S37" line="g47" valid="true">Lot durch S37 zu g47</Plumb>
<Line name="g48" n="175" hidden="super" from="P1" to="S38">Gerade durch P1 und S38</Line>
<Intersection name="S42" n="176" hidden="super" first="l40" second="g48">Schnitt zwischen l40 und g48</Intersection>
<Circle name="k10" n="177" hidden="super" through="S37" midpoint="S42" acute="true">Kreis um S42 durch S37</Circle>
<Line name="g49" n="178" hidden="super" from="P1" to="S37">Gerade durch P1 und S37</Line>
<Midpoint name="M35" n="179" hidden="super" first="P1" second="S37">Mitte zwischen P1 und S37</Midpoint>
<Plumb name="l41" n="180" hidden="super" point="M35" line="g49" valid="true">Lot durch M35 zu g49</Plumb>
<Intersection name="S43" n="181" hidden="super" first="l41" second="k" which="second">Schnitt zwischen l41 und k</Intersection>
<Line name="g50" n="182" hidden="super" from="P1" to="S43">Gerade durch P1 und S43</Line>
<Midpoint name="M36" n="183" hidden="super" first="P1" second="S43">Mitte zwischen P1 und S43</Midpoint>
<Plumb name="l42" n="184" hidden="super" point="M36" line="g50" valid="true">Lot durch M36 zu g50</Plumb>
<Intersection name="S44" n="185" hidden="super" first="g49" second="l42">Schnitt zwischen g49 und l42</Intersection>
<Line name="g51" n="186" hidden="super" from="S37" to="S38">Gerade durch S37 und S38</Line>
<Midpoint name="M37" n="187" hidden="super" first="S37" second="S38">Mitte zwischen S37 und S38</Midpoint>
<Plumb name="l43" n="188" hidden="super" point="M37" line="g51" valid="true">Lot durch M37 zu g51</Plumb>
<Line name="g52" n="189" hidden="super" from="S37" to="S44">Gerade durch S37 und S44</Line>
<Midpoint name="M38" n="190" hidden="super" first="S37" second="S44">Mitte zwischen S37 und S44</Midpoint>
<Plumb name="l44" n="191" hidden="super" point="M38" line="g52" valid="true">Lot durch M38 zu g52</Plumb>
<Intersection name="S45" n="192" hidden="super" first="l43" second="l44">Schnitt zwischen l43 und l44</Intersection>
<Line name="g53" n="193" hidden="super" from="S45" to="S38">Gerade durch S45 und S38</Line>
<Plumb name="l45" n="194" hidden="super" point="S38" line="g53" valid="true">Lot durch S38 zu g53</Plumb>
<Line name="g54" n="195" hidden="super" from="P1" to="S37">Gerade durch P1 und S37</Line>
<Intersection name="S46" n="196" hidden="super" first="l45" second="g54">Schnitt zwischen l45 und g54</Intersection>
<Circle name="k11" n="197" hidden="super" through="S38" midpoint="S46" acute="true">Kreis um S46 durch S38</Circle>
<Intersection name="S47" n="198" hidden="super" first="k10" second="k11" which="first">Schnitt zwischen k10 und k11</Intersection>
<Intersection name="S48" n="199" hidden="super" first="k10" second="k11" which="second">Schnitt zwischen k10 und k11</Intersection>
<Line name="g55" n="200" hidden="super" from="P1" to="S48">Gerade durch P1 und S48</Line>
<Midpoint name="M39" n="201" hidden="super" first="P1" second="S48">Mitte zwischen P1 und S48</Midpoint>
<Plumb name="l46" n="202" hidden="super" point="M39" line="g55" valid="true">Lot durch M39 zu g55</Plumb>
<Intersection name="S49" n="203" hidden="super" first="l46" second="k" which="second">Schnitt zwischen l46 und k</Intersection>
<Line name="g56" n="204" hidden="super" from="P1" to="S49">Gerade durch P1 und S49</Line>
<Midpoint name="M40" n="205" hidden="super" first="P1" second="S49">Mitte zwischen P1 und S49</Midpoint>
<Plumb name="l47" n="206" hidden="super" point="M40" line="g56" valid="true">Lot durch M40 zu g56</Plumb>
<Intersection name="S50" n="207" hidden="super" first="g55" second="l47">Schnitt zwischen g55 und l47</Intersection>
<Line name="g57" n="208" hidden="super" from="S48" to="S47">Gerade durch S48 und S47</Line>
<Midpoint name="M41" n="209" hidden="super" first="S48" second="S47">Mitte zwischen S48 und S47</Midpoint>
<Plumb name="l48" n="210" hidden="super" point="M41" line="g57" valid="true">Lot durch M41 zu g57</Plumb>
<Line name="g58" n="211" hidden="super" from="S48" to="S50">Gerade durch S48 und S50</Line>
<Midpoint name="M42" n="212" hidden="super" first="S48" second="S50">Mitte zwischen S48 und S50</Midpoint>
<Plumb name="l49" n="213" hidden="super" point="M42" line="g58" valid="true">Lot durch M42 zu g58</Plumb>
<Intersection name="S51" n="214" hidden="super" first="l48" second="l49">Schnitt zwischen l48 und l49</Intersection>
<Circle name="k12" n="215" hidden="super" through="S48" midpoint="S51" acute="true">Kreis um S51 durch S48</Circle>
<Intersection name="S52" n="216" hidden="super" first="k12" second="k8" closeto="P1" which="first">Schnitt zwischen k12 und k8</Intersection>
<Line name="g59" n="217" hidden="super" from="P1" to="P26">Gerade durch P1 und P26</Line>
<Midpoint name="M43" n="218" hidden="super" first="P1" second="P26">Mitte zwischen P1 und P26</Midpoint>
<Plumb name="l50" n="219" hidden="super" point="M43" line="g59" valid="true">Lot durch M43 zu g59</Plumb>
<Intersection name="S53" n="220" hidden="super" first="l50" second="k" which="second">Schnitt zwischen l50 und k</Intersection>
<Line name="g60" n="221" hidden="super" from="P1" to="S53">Gerade durch P1 und S53</Line>
<Midpoint name="M44" n="222" hidden="super" first="P1" second="S53">Mitte zwischen P1 und S53</Midpoint>
<Plumb name="l51" n="223" hidden="super" point="M44" line="g60" valid="true">Lot durch M44 zu g60</Plumb>
<Intersection name="S54" n="224" hidden="super" first="g59" second="l51">Schnitt zwischen g59 und l51</Intersection>
<Line name="g61" n="225" hidden="super" from="P26" to="S52">Gerade durch P26 und S52</Line>
<Midpoint name="M45" n="226" hidden="super" first="P26" second="S52">Mitte zwischen P26 und S52</Midpoint>
<Plumb name="l52" n="227" hidden="super" point="M45" line="g61" valid="true">Lot durch M45 zu g61</Plumb>
<Line name="g62" n="228" hidden="super" from="P26" to="S54">Gerade durch P26 und S54</Line>
<Midpoint name="M46" n="229" hidden="super" first="P26" second="S54">Mitte zwischen P26 und S54</Midpoint>
<Plumb name="l53" n="230" hidden="super" point="M46" line="g62" valid="true">Lot durch M46 zu g62</Plumb>
<Intersection name="S55" n="231" hidden="super" first="l52" second="l53">Schnitt zwischen l52 und l53</Intersection>
<Line name="g63" n="232" hidden="super" from="S55" to="S52">Gerade durch S55 und S52</Line>
<Plumb name="l54" n="233" hidden="super" point="S52" line="g63" valid="true">Lot durch S52 zu g63</Plumb>
<Line name="g64" n="234" hidden="super" from="P1" to="P26">Gerade durch P1 und P26</Line>
<Intersection name="S56" n="235" hidden="super" first="l54" second="g64">Schnitt zwischen l54 und g64</Intersection>
<Circle name="k13" n="236" target="true" through="S52" midpoint="S56" acute="true">Kreis um S56 durch S52</Circle>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/07: Middle perpendicular (1)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="P17">A</Parameter>
<Parameter name="P16">B</Parameter>
<Comment>
<P>Perpendicular in the middle of the line segment AB.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P16" n="2" mainparameter="true" x="-2.5576408023818145" y="-1.4837158542478237">Point at -2.55764, -1.48372</Point>
<Point name="P17" n="3" mainparameter="true" x="3.7761600000000004" y="0.26609000000000005">Point at 3.77616, 0.26609</Point>
<Line name="g1" n="4" hidden="super" from="P1" to="P16">Gerade durch P1 und P16</Line>
<Midpoint name="M1" n="5" hidden="super" first="P1" second="P16">Mitte zwischen P1 und P16</Midpoint>
<Plumb name="l1" n="6" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="7" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="8" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="9" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="10" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="11" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="12" hidden="super" from="P16" to="P17">Gerade durch P16 und P17</Line>
<Midpoint name="M3" n="13" hidden="super" first="P16" second="P17">Mitte zwischen P16 und P17</Midpoint>
<Plumb name="l3" n="14" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="15" hidden="super" from="P16" to="S2">Gerade durch P16 und S2</Line>
<Midpoint name="M4" n="16" hidden="super" first="P16" second="S2">Mitte zwischen P16 und S2</Midpoint>
<Plumb name="l4" n="17" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="18" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Line name="g5" n="19" hidden="super" from="S3" to="P17">Gerade durch S3 und P17</Line>
<Plumb name="l5" n="20" hidden="super" point="P17" line="g5" valid="true">Lot durch P17 zu g5</Plumb>
<Line name="g6" n="21" hidden="super" from="P1" to="P16">Gerade durch P1 und P16</Line>
<Intersection name="S4" n="22" hidden="super" first="l5" second="g6">Schnitt zwischen l5 und g6</Intersection>
<Circle name="k2" n="23" hidden="super" through="P17" midpoint="S4" acute="true">Kreis um S4 durch P17</Circle>
<Line name="g7" n="24" hidden="super" from="P1" to="P17">Gerade durch P1 und P17</Line>
<Midpoint name="M5" n="25" hidden="super" first="P1" second="P17">Mitte zwischen P1 und P17</Midpoint>
<Plumb name="l6" n="26" hidden="super" point="M5" line="g7" valid="true">Lot durch M5 zu g7</Plumb>
<Intersection name="S5" n="27" hidden="super" first="l6" second="k" which="second">Schnitt zwischen l6 und k</Intersection>
<Line name="g8" n="28" hidden="super" from="P1" to="S5">Gerade durch P1 und S5</Line>
<Midpoint name="M6" n="29" hidden="super" first="P1" second="S5">Mitte zwischen P1 und S5</Midpoint>
<Plumb name="l7" n="30" hidden="super" point="M6" line="g8" valid="true">Lot durch M6 zu g8</Plumb>
<Intersection name="S6" n="31" hidden="super" first="g7" second="l7">Schnitt zwischen g7 und l7</Intersection>
<Line name="g9" n="32" hidden="super" from="P17" to="P16">Gerade durch P17 und P16</Line>
<Midpoint name="M7" n="33" hidden="super" first="P17" second="P16">Mitte zwischen P17 und P16</Midpoint>
<Plumb name="l8" n="34" hidden="super" point="M7" line="g9" valid="true">Lot durch M7 zu g9</Plumb>
<Line name="g10" n="35" hidden="super" from="P17" to="S6">Gerade durch P17 und S6</Line>
<Midpoint name="M8" n="36" hidden="super" first="P17" second="S6">Mitte zwischen P17 und S6</Midpoint>
<Plumb name="l9" n="37" hidden="super" point="M8" line="g10" valid="true">Lot durch M8 zu g10</Plumb>
<Intersection name="S7" n="38" hidden="super" first="l8" second="l9">Schnitt zwischen l8 und l9</Intersection>
<Line name="g11" n="39" hidden="super" from="S7" to="P16">Gerade durch S7 und P16</Line>
<Plumb name="l10" n="40" hidden="super" point="P16" line="g11" valid="true">Lot durch P16 zu g11</Plumb>
<Line name="g12" n="41" hidden="super" from="P1" to="P17">Gerade durch P1 und P17</Line>
<Intersection name="S8" n="42" hidden="super" first="l10" second="g12">Schnitt zwischen l10 und g12</Intersection>
<Circle name="k3" n="43" hidden="super" through="P16" midpoint="S8" acute="true">Kreis um S8 durch P16</Circle>
<Intersection name="S9" n="44" hidden="super" first="k2" second="k3" which="first">Schnitt zwischen k2 und k3</Intersection>
<Intersection name="S10" n="45" hidden="super" first="k2" second="k3" which="second">Schnitt zwischen k2 und k3</Intersection>
<Line name="g13" n="46" hidden="super" from="P1" to="S10">Gerade durch P1 und S10</Line>
<Midpoint name="M9" n="47" hidden="super" first="P1" second="S10">Mitte zwischen P1 und S10</Midpoint>
<Plumb name="l11" n="48" hidden="super" point="M9" line="g13" valid="true">Lot durch M9 zu g13</Plumb>
<Intersection name="S11" n="49" hidden="super" first="l11" second="k" which="second">Schnitt zwischen l11 und k</Intersection>
<Line name="g14" n="50" hidden="super" from="P1" to="S11">Gerade durch P1 und S11</Line>
<Midpoint name="M10" n="51" hidden="super" first="P1" second="S11">Mitte zwischen P1 und S11</Midpoint>
<Plumb name="l12" n="52" hidden="super" point="M10" line="g14" valid="true">Lot durch M10 zu g14</Plumb>
<Intersection name="S12" n="53" hidden="super" first="g13" second="l12">Schnitt zwischen g13 und l12</Intersection>
<Line name="g15" n="54" hidden="super" from="S10" to="S9">Gerade durch S10 und S9</Line>
<Midpoint name="M11" n="55" hidden="super" first="S10" second="S9">Mitte zwischen S10 und S9</Midpoint>
<Plumb name="l13" n="56" hidden="super" point="M11" line="g15" valid="true">Lot durch M11 zu g15</Plumb>
<Line name="g16" n="57" hidden="super" from="S10" to="S12">Gerade durch S10 und S12</Line>
<Midpoint name="M12" n="58" hidden="super" first="S10" second="S12">Mitte zwischen S10 und S12</Midpoint>
<Plumb name="l14" n="59" hidden="super" point="M12" line="g16" valid="true">Lot durch M12 zu g16</Plumb>
<Intersection name="S13" n="60" hidden="super" first="l13" second="l14">Schnitt zwischen l13 und l14</Intersection>
<Circle name="k4" n="61" target="true" through="S10" midpoint="S13" start="S15" end="S14" acute="true">Kreis um S13 durch S10</Circle>
<Intersection name="S14" n="62" hidden="true" target="true" first="k4" second="k" which="first">Schnitt zwischen k4 und k</Intersection>
<Intersection name="S15" n="63" hidden="true" target="true" first="k" second="k4" which="first">Schnitt zwischen k und k4</Intersection>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/09: Continuous intersection (26)">
<Parameter name="k">=k</Parameter>
<Parameter name="k2">g</Parameter>
<Parameter name="k3">h</Parameter>
<Comment>
<P>Intersection of two Poincare lines, continuously selected.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" midpoint="P1">???</Circle>
<Point name="P2" n="2" hidden="true" x="7.833634091260263" y="17.633681484258574">Point at 7.83363, 17.63368</Point>
<Circle name="k2" n="3" midpoint="P2">???</Circle>
<Point name="P3" n="4" hidden="true" x="36.220717721156106" y="-23.318115766578146">Point at 36.22072, -23.31812</Point>
<Circle name="k3" n="5" midpoint="P3">???</Circle>
<Intersection name="S1" n="6" color="2" target="true" first="k3" second="k2" shape="circle" which="second">Schnitt zwischen k3 und k2</Intersection>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/09: Intersection (26)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="k20">g</Parameter>
<Parameter name="k21">h</Parameter>
<Comment>
<P>Intersection of two lines choosing the intersection in the
basic circle.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P2" n="2" hidden="true" parameter="true" x="-21.646621037458292" y="9.988074239800529">Point at -21.64662, 9.98807</Point>
<Circle name="k20" n="3" mainparameter="true" midpoint="P2">???</Circle>
<Point name="P3" n="4" hidden="true" parameter="true" x="165.47172800155641" y="241.77451335404612">Point at 165.47173, 241.77451</Point>
<Circle name="k21" n="5" mainparameter="true" midpoint="P3">???</Circle>
<Intersection name="S1" n="6" target="true" first="k20" second="k21" closeto="P1" which="second">Schnitt zwischen k20 und k21</Intersection>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/10: Perpendicular (33)">
<Parameter name="k" fixed="k">k</Parameter>
<Parameter name="k6">g</Parameter>
<Parameter name="P12">P</Parameter>
<Comment>
<P>Perpendicular on g through P.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P2" n="2" hidden="true" parameter="true" x="8.464433689056246" y="4.067550156444892">Point at 8.46443, 4.06755</Point>
<Circle name="k6" n="3" mainparameter="true" midpoint="P2">???</Circle>
<Point name="P12" n="4" mainparameter="true" x="-2.90267" y="4.0367900000000025">Point at -2.90267, 4.03679</Point>
<Line name="g1" n="5" hidden="super" from="P1" to="P2">Gerade durch P1 und P2</Line>
<Intersection name="S1" n="6" hidden="super" first="g1" second="k6" closeto="P1" which="second">Schnitt zwischen g1 und k6</Intersection>
<Line name="g2" n="7" hidden="super" from="P1" to="P12">Gerade durch P1 und P12</Line>
<Midpoint name="M1" n="8" hidden="super" first="P1" second="P12">Mitte zwischen P1 und P12</Midpoint>
<Plumb name="l1" n="9" hidden="super" point="M1" line="g2" valid="true">Lot durch M1 zu g2</Plumb>
<Intersection name="S2" n="10" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g3" n="11" hidden="super" from="P1" to="S2">Gerade durch P1 und S2</Line>
<Midpoint name="M2" n="12" hidden="super" first="P1" second="S2">Mitte zwischen P1 und S2</Midpoint>
<Plumb name="l2" n="13" hidden="super" point="M2" line="g3" valid="true">Lot durch M2 zu g3</Plumb>
<Intersection name="S3" n="14" hidden="super" first="g2" second="l2">Schnitt zwischen g2 und l2</Intersection>
<Line name="g4" n="15" hidden="super" from="P12" to="S1">Gerade durch P12 und S1</Line>
<Midpoint name="M3" n="16" hidden="super" first="P12" second="S1">Mitte zwischen P12 und S1</Midpoint>
<Plumb name="l3" n="17" hidden="super" point="M3" line="g4" valid="true">Lot durch M3 zu g4</Plumb>
<Line name="g5" n="18" hidden="super" from="P12" to="S3">Gerade durch P12 und S3</Line>
<Midpoint name="M4" n="19" hidden="super" first="P12" second="S3">Mitte zwischen P12 und S3</Midpoint>
<Plumb name="l4" n="20" hidden="super" point="M4" line="g5" valid="true">Lot durch M4 zu g5</Plumb>
<Intersection name="S4" n="21" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Line name="g6" n="22" hidden="super" from="S4" to="S1">Gerade durch S4 und S1</Line>
<Plumb name="l5" n="23" hidden="super" point="S1" line="g6" valid="true">Lot durch S1 zu g6</Plumb>
<Line name="g7" n="24" hidden="super" from="P1" to="P12">Gerade durch P1 und P12</Line>
<Intersection name="S5" n="25" hidden="super" first="l5" second="g7">Schnitt zwischen l5 und g7</Intersection>
<Circle name="k3" n="26" hidden="super" through="S1" midpoint="S5" acute="true">Kreis um S5 durch S1</Circle>
<Intersection name="S6" n="27" hidden="super" first="k6" second="k3" valid="true" which="first">Schnitt zwischen k6 und k3</Intersection>
<Intersection name="S7" n="28" hidden="super" first="k6" second="k3" valid="true" which="second">Schnitt zwischen k6 und k3</Intersection>
<Line name="g8" n="29" hidden="super" from="P1" to="S7">Gerade durch P1 und S7</Line>
<Midpoint name="M5" n="30" hidden="super" first="P1" second="S7">Mitte zwischen P1 und S7</Midpoint>
<Plumb name="l6" n="31" hidden="super" point="M5" line="g8" valid="true">Lot durch M5 zu g8</Plumb>
<Intersection name="S8" n="32" hidden="super" first="l6" second="k" which="second">Schnitt zwischen l6 und k</Intersection>
<Line name="g9" n="33" hidden="super" from="P1" to="S8">Gerade durch P1 und S8</Line>
<Midpoint name="M6" n="34" hidden="super" first="P1" second="S8">Mitte zwischen P1 und S8</Midpoint>
<Plumb name="l7" n="35" hidden="super" point="M6" line="g9" valid="true">Lot durch M6 zu g9</Plumb>
<Intersection name="S9" n="36" hidden="super" first="g8" second="l7">Schnitt zwischen g8 und l7</Intersection>
<Line name="g10" n="37" hidden="super" from="S7" to="S6">Gerade durch S7 und S6</Line>
<Midpoint name="M7" n="38" hidden="super" first="S7" second="S6">Mitte zwischen S7 und S6</Midpoint>
<Plumb name="l8" n="39" hidden="super" point="M7" line="g10" valid="true">Lot durch M7 zu g10</Plumb>
<Line name="g11" n="40" hidden="super" from="S7" to="S9">Gerade durch S7 und S9</Line>
<Midpoint name="M8" n="41" hidden="super" first="S7" second="S9">Mitte zwischen S7 und S9</Midpoint>
<Plumb name="l9" n="42" hidden="super" point="M8" line="g11" valid="true">Lot durch M8 zu g11</Plumb>
<Intersection name="S10" n="43" hidden="super" first="l8" second="l9">Schnitt zwischen l8 und l9</Intersection>
<Line name="g12" n="44" hidden="super" from="S10" to="S6">Gerade durch S10 und S6</Line>
<Plumb name="l10" n="45" hidden="super" point="S6" line="g12" valid="true">Lot durch S6 zu g12</Plumb>
<Line name="g13" n="46" hidden="super" from="P1" to="S7">Gerade durch P1 und S7</Line>
<Intersection name="S11" n="47" hidden="super" first="l10" second="g13">Schnitt zwischen l10 und g13</Intersection>
<Circle name="k4" n="48" hidden="super" through="S6" midpoint="S11" acute="true">Kreis um S11 durch S6</Circle>
<Line name="g14" n="49" hidden="super" from="P1" to="S6">Gerade durch P1 und S6</Line>
<Midpoint name="M9" n="50" hidden="super" first="P1" second="S6">Mitte zwischen P1 und S6</Midpoint>
<Plumb name="l11" n="51" hidden="super" point="M9" line="g14" valid="true">Lot durch M9 zu g14</Plumb>
<Intersection name="S12" n="52" hidden="super" first="l11" second="k" which="second">Schnitt zwischen l11 und k</Intersection>
<Line name="g15" n="53" hidden="super" from="P1" to="S12">Gerade durch P1 und S12</Line>
<Midpoint name="M10" n="54" hidden="super" first="P1" second="S12">Mitte zwischen P1 und S12</Midpoint>
<Plumb name="l12" n="55" hidden="super" point="M10" line="g15" valid="true">Lot durch M10 zu g15</Plumb>
<Intersection name="S13" n="56" hidden="super" first="g14" second="l12">Schnitt zwischen g14 und l12</Intersection>
<Line name="g16" n="57" hidden="super" from="S6" to="S7">Gerade durch S6 und S7</Line>
<Midpoint name="M11" n="58" hidden="super" first="S6" second="S7">Mitte zwischen S6 und S7</Midpoint>
<Plumb name="l13" n="59" hidden="super" point="M11" line="g16" valid="true">Lot durch M11 zu g16</Plumb>
<Line name="g17" n="60" hidden="super" from="S6" to="S13">Gerade durch S6 und S13</Line>
<Midpoint name="M12" n="61" hidden="super" first="S6" second="S13">Mitte zwischen S6 und S13</Midpoint>
<Plumb name="l14" n="62" hidden="super" point="M12" line="g17" valid="true">Lot durch M12 zu g17</Plumb>
<Intersection name="S14" n="63" hidden="super" first="l13" second="l14">Schnitt zwischen l13 und l14</Intersection>
<Line name="g18" n="64" hidden="super" from="S14" to="S7">Gerade durch S14 und S7</Line>
<Plumb name="l15" n="65" hidden="super" point="S7" line="g18" valid="true">Lot durch S7 zu g18</Plumb>
<Line name="g19" n="66" hidden="super" from="P1" to="S6">Gerade durch P1 und S6</Line>
<Intersection name="S15" n="67" hidden="super" first="l15" second="g19">Schnitt zwischen l15 und g19</Intersection>
<Circle name="k5" n="68" hidden="super" through="S7" midpoint="S15" acute="true">Kreis um S15 durch S7</Circle>
<Intersection name="S16" n="69" hidden="super" first="k4" second="k5" which="first">Schnitt zwischen k4 und k5</Intersection>
<Intersection name="S17" n="70" hidden="super" first="k4" second="k5" which="second">Schnitt zwischen k4 und k5</Intersection>
<Line name="g20" n="71" hidden="super" from="P1" to="S17">Gerade durch P1 und S17</Line>
<Midpoint name="M13" n="72" hidden="super" first="P1" second="S17">Mitte zwischen P1 und S17</Midpoint>
<Plumb name="l16" n="73" hidden="super" point="M13" line="g20" valid="true">Lot durch M13 zu g20</Plumb>
<Intersection name="S18" n="74" hidden="super" first="l16" second="k" which="second">Schnitt zwischen l16 und k</Intersection>
<Line name="g21" n="75" hidden="super" from="P1" to="S18">Gerade durch P1 und S18</Line>
<Midpoint name="M14" n="76" hidden="super" first="P1" second="S18">Mitte zwischen P1 und S18</Midpoint>
<Plumb name="l17" n="77" hidden="super" point="M14" line="g21" valid="true">Lot durch M14 zu g21</Plumb>
<Intersection name="S19" n="78" hidden="super" first="g20" second="l17">Schnitt zwischen g20 und l17</Intersection>
<Line name="g22" n="79" hidden="super" from="S17" to="S16">Gerade durch S17 und S16</Line>
<Midpoint name="M15" n="80" hidden="super" first="S17" second="S16">Mitte zwischen S17 und S16</Midpoint>
<Plumb name="l18" n="81" hidden="super" point="M15" line="g22" valid="true">Lot durch M15 zu g22</Plumb>
<Line name="g23" n="82" hidden="super" from="S17" to="S19">Gerade durch S17 und S19</Line>
<Midpoint name="M16" n="83" hidden="super" first="S17" second="S19">Mitte zwischen S17 und S19</Midpoint>
<Plumb name="l19" n="84" hidden="super" point="M16" line="g23" valid="true">Lot durch M16 zu g23</Plumb>
<Intersection name="S20" n="85" hidden="super" first="l18" second="l19">Schnitt zwischen l18 und l19</Intersection>
<Circle name="k7" n="86" target="true" through="S17" midpoint="S20" start="S21" end="S22" acute="true">Kreis um S20 durch S17</Circle>
<Intersection name="S21" n="87" hidden="true" target="true" first="k7" second="k" which="first">Schnitt zwischen k7 und k</Intersection>
<Intersection name="S22" n="88" hidden="true" target="true" first="k" second="k7" which="first">Schnitt zwischen k und k7</Intersection>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/11: Angle (14)">
<Parameter name="k">=k</Parameter>
<Parameter name="P7">A</Parameter>
<Parameter name="P8">B</Parameter>
<Parameter name="P9">C</Parameter>
<Comment>
<P>Angle ABC oriented into mathematically positive direction.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P7" n="2" mainparameter="true" x="2.0173767878965965" y="-1.8584498966338545">Point at 2.01738, -1.85845</Point>
<Point name="P8" n="3" mainparameter="true" x="-3.7329138872268053" y="0.39166384580573693">Point at -3.73291, 0.39166</Point>
<Point name="P9" n="4" mainparameter="true" x="-2.482850696982587" y="4.43032953736398">Point at -2.48285, 4.43033</Point>
<Line name="g1" n="5" color="1" hidden="super" from="P1" to="P8">Gerade durch P1 und P8</Line>
<Midpoint name="M1" n="6" color="1" hidden="super" first="P1" second="P8">Mitte zwischen P1 und P8</Midpoint>
<Plumb name="l1" n="7" color="1" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="8" color="1" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="9" color="1" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="10" color="1" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="11" color="1" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="12" color="1" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="13" color="1" hidden="super" from="P8" to="P7">Gerade durch P8 und P7</Line>
<Midpoint name="M3" n="14" color="1" hidden="super" first="P8" second="P7">Mitte zwischen P8 und P7</Midpoint>
<Plumb name="l3" n="15" color="1" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="16" color="1" hidden="super" from="P8" to="S2">Gerade durch P8 und S2</Line>
<Midpoint name="M4" n="17" color="1" hidden="super" first="P8" second="S2">Mitte zwischen P8 und S2</Midpoint>
<Plumb name="l4" n="18" color="1" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="19" color="1" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Line name="g5" n="20" color="1" hidden="super" from="P8" to="S3">Gerade durch P8 und S3</Line>
<Plumb name="l5" n="21" color="1" hidden="super" point="P8" line="g5" valid="true">Lot durch P8 zu g5</Plumb>
<Plumb name="l6" n="22" color="1" hidden="super" point="P7" line="l5" valid="true">Lot durch P7 zu l5</Plumb>
<Intersection name="S4" n="23" color="1" hidden="super" first="l5" second="l6">Schnitt zwischen l5 und l6</Intersection>
<Line name="g6" n="24" color="1" hidden="super" from="P1" to="P8">Gerade durch P1 und P8</Line>
<Midpoint name="M5" n="25" color="1" hidden="super" first="P1" second="P8">Mitte zwischen P1 und P8</Midpoint>
<Plumb name="l7" n="26" color="1" hidden="super" point="M5" line="g6" valid="true">Lot durch M5 zu g6</Plumb>
<Intersection name="S5" n="27" color="1" hidden="super" first="l7" second="k" which="second">Schnitt zwischen l7 und k</Intersection>
<Line name="g7" n="28" color="1" hidden="super" from="P1" to="S5">Gerade durch P1 und S5</Line>
<Midpoint name="M6" n="29" color="1" hidden="super" first="P1" second="S5">Mitte zwischen P1 und S5</Midpoint>
<Plumb name="l8" n="30" color="1" hidden="super" point="M6" line="g7" valid="true">Lot durch M6 zu g7</Plumb>
<Intersection name="S6" n="31" color="1" hidden="super" first="g6" second="l8">Schnitt zwischen g6 und l8</Intersection>
<Line name="g8" n="32" color="1" hidden="super" from="P8" to="P9">Gerade durch P8 und P9</Line>
<Midpoint name="M7" n="33" color="1" hidden="super" first="P8" second="P9">Mitte zwischen P8 und P9</Midpoint>
<Plumb name="l9" n="34" color="1" hidden="super" point="M7" line="g8" valid="true">Lot durch M7 zu g8</Plumb>
<Line name="g9" n="35" color="1" hidden="super" from="P8" to="S6">Gerade durch P8 und S6</Line>
<Midpoint name="M8" n="36" color="1" hidden="super" first="P8" second="S6">Mitte zwischen P8 und S6</Midpoint>
<Plumb name="l10" n="37" color="1" hidden="super" point="M8" line="g9" valid="true">Lot durch M8 zu g9</Plumb>
<Intersection name="S7" n="38" color="1" hidden="super" first="l9" second="l10">Schnitt zwischen l9 und l10</Intersection>
<Line name="g10" n="39" color="1" hidden="super" from="P8" to="S7">Gerade durch P8 und S7</Line>
<Plumb name="l11" n="40" color="1" hidden="super" point="P8" line="g10" valid="true">Lot durch P8 zu g10</Plumb>
<Plumb name="l12" n="41" color="1" hidden="super" point="P9" line="l11" valid="true">Lot durch P9 zu l11</Plumb>
<Intersection name="S8" n="42" color="1" hidden="super" first="l11" second="l12">Schnitt zwischen l11 und l12</Intersection>
<Angle name="w1" n="43" color="1" target="true" first="S4" root="P8" second="S8">Winkel S4 - P8 - S8</Angle>
</Objects>
</Macro>
<Macro Name="Poincare Geometry/12: Fixed Angle (21)">
<Parameter name="k">=k</Parameter>
<Parameter name="P10">A</Parameter>
<Parameter name="P11">B</Parameter>
<Comment>
<P>Angle at B on AB with fixed value.</P>
</Comment>
<Objects>
<Point name="P1" n="0" hidden="true" parameter="true" x="0.0" y="0.0">Point at 0.0, 0.0</Point>
<Circle name="k" n="1" mainparameter="true" midpoint="P1">???</Circle>
<Point name="P10" n="2" mainparameter="true" x="-0.9827748686895241" y="1.160933501340642">Point at -0.98277, 1.16093</Point>
<Point name="P11" n="3" mainparameter="true" x="3.6520748059082693" y="0.6224447424662105">Point at 3.65207, 0.62244</Point>
<Line name="g1" n="4" color="1" hidden="super" from="P1" to="P10">Gerade durch P1 und P10</Line>
<Midpoint name="M1" n="5" color="1" hidden="super" first="P1" second="P10">Mitte zwischen P1 und P10</Midpoint>
<Plumb name="l1" n="6" color="1" hidden="super" point="M1" line="g1" valid="true">Lot durch M1 zu g1</Plumb>
<Intersection name="S1" n="7" color="1" hidden="super" first="l1" second="k" which="second">Schnitt zwischen l1 und k</Intersection>
<Line name="g2" n="8" color="1" hidden="super" from="P1" to="S1">Gerade durch P1 und S1</Line>
<Midpoint name="M2" n="9" color="1" hidden="super" first="P1" second="S1">Mitte zwischen P1 und S1</Midpoint>
<Plumb name="l2" n="10" color="1" hidden="super" point="M2" line="g2" valid="true">Lot durch M2 zu g2</Plumb>
<Intersection name="S2" n="11" color="1" hidden="super" first="g1" second="l2">Schnitt zwischen g1 und l2</Intersection>
<Line name="g3" n="12" color="1" hidden="super" from="P10" to="P11">Gerade durch P10 und P11</Line>
<Midpoint name="M3" n="13" color="1" hidden="super" first="P10" second="P11">Mitte zwischen P10 und P11</Midpoint>
<Plumb name="l3" n="14" color="1" hidden="super" point="M3" line="g3" valid="true">Lot durch M3 zu g3</Plumb>
<Line name="g4" n="15" color="1" hidden="super" from="P10" to="S2">Gerade durch P10 und S2</Line>
<Midpoint name="M4" n="16" color="1" hidden="super" first="P10" second="S2">Mitte zwischen P10 und S2</Midpoint>
<Plumb name="l4" n="17" color="1" hidden="super" point="M4" line="g4" valid="true">Lot durch M4 zu g4</Plumb>
<Intersection name="S3" n="18" color="1" hidden="super" first="l3" second="l4">Schnitt zwischen l3 und l4</Intersection>
<Line name="g5" n="19" hidden="super" from="S3" to="P10">Gerade durch S3 und P10</Line>
<Line name="g6" n="20" hidden="super" from="S3" to="P11">Gerade durch S3 und P11</Line>
<Plumb name="l5" n="21" hidden="super" point="P11" line="g6" valid="true">Lot durch P11 zu g6</Plumb>
<Plumb name="l6" n="22" hidden="super" point="P10" line="g5" valid="true">Lot durch P10 zu g5</Plumb>
<Intersection name="S4" n="23" hidden="super" first="l6" second="l5" shape="circle">Schnitt zwischen l6 und l5</Intersection>
<Angle name="w1" n="24" target="true" first="S4" root="P11" fixedangle="true" fixed="45" reduced="true">Angle S4 - P11 with size 45</Angle>
<Plumb name="l7" n="25" hidden="super" point="P11" line="w1" valid="true">Lot durch P11 zu w1</Plumb>
<Ray name="r1" n="26" hidden="super" from="P1" to="P11">Strahl von P1 in Richtung P11</Ray>
<Circle name="k2" n="27" hidden="super" fixed="k^2/d(P11,P1)" midpoint="P1" acute="true">Kreis um P1 mit Radius k^2/d(P11,P1)</Circle>
<Intersection name="S5" n="28" hidden="super" first="r1" second="k2" shape="circle" which="first">Schnitt zwischen r1 und k2</Intersection>
<Circle name="k3" n="29" hidden="super" through="S5" midpoint="P11" acute="true">Kreis um P11 durch S5</Circle>
<Circle name="k4" n="30" hidden="super" through="P11" midpoint="S5" acute="true">Kreis um S5 durch P11</Circle>
<Intersection name="S6" n="31" hidden="super" first="k3" second="k4" which="second">Schnitt zwischen k3 und k4</Intersection>
<Intersection name="S7" n="32" hidden="super" first="k4" second="k3" which="second">Schnitt zwischen k4 und k3</Intersection>
<Line name="g7" n="33" hidden="super" from="S6" to="S7">Gerade durch S6 und S7</Line>
<Intersection name="S8" n="34" hidden="super" first="g7" second="l7" shape="circle">Schnitt zwischen g7 und l7</Intersection>
<Circle name="k5" n="35" target="true" through="P11" midpoint="S8" acute="true">Kreis um S8 durch P11</Circle>
</Objects>
<PromptFor object0="w1" prompt0="w"/>
</Macro>
<Construction job="true" last="P4" target1="c25">
<Window x="0.35844919012283327" y="-0.05720338860737417" w="7.204412273296672"/>
<Comment>
<P>Poincare (hyperbolic) geometry realized with macros. </P>
<P></P>
<P>This geometry can be realized on the southern hemisphere of
a ball. You are viewing at it from the north pole. The
green circle is the projection of the southern hemisphere,
the boundary is the equator. This projection is called
stereographical projection. It preserves angles. </P>
<P></P>
<P>Lines are circles on the ball, rectangular to the equator.
These circles project to circles perpendicular to the
boundary of the green circle. Circles are just circles on
the ball. They project to circles, but with different
midpoint. </P>
<P></P>
<P>Take care to use the macro for intersections. It will
intersect two lines (circles in the projection), but choose
the intersection in the green circle.</P>
</Comment>
<Objects>
<Point name="Mc" n="0" hidden="true" x="0" actx="0.0" y="0" acty="0.0" fixed="true">Point at &quot;0&quot;, &quot;0&quot;</Point>
<Circle name="k" n="1" color="1" type="thin" background="true" fixed="1+5" midpoint="Mc" filled="true">Kreis um Mc mit Radius 1+5</Circle>
<Point name="P2" n="1" x="-2.058820717364866" y="-3.375024830257157" shape="circle">Point at -2.05882, -3.37502</Point>
<Point name="P3" n="2" x="1.1879045505352792" y="-2.071594978180457" shape="circle">Point at 1.1879, -2.07159</Point>
<Line name="l1" n="3" hidden="super" from="Mc" to="P2">Line through Mc and P2</Line>
<Midpoint name="M1" n="4" hidden="super" first="Mc" second="P2">Midpoint between Mc and P2</Midpoint>
<Plumb name="p1" n="5" hidden="super" point="M1" line="l1" valid="true">Perpendicular line through M1 to l1</Plumb>
<Intersection name="I1" n="6" hidden="super" first="p1" second="k" which="second">Intersection between p1 and k</Intersection>
<Line name="l2" n="7" hidden="super" from="Mc" to="I1">Line through Mc and I1</Line>
<Midpoint name="M2" n="8" hidden="super" first="Mc" second="I1">Midpoint between Mc and I1</Midpoint>
<Plumb name="p2" n="9" hidden="super" point="M2" line="l2" valid="true">Perpendicular line through M2 to l2</Plumb>
<Intersection name="I2" n="10" hidden="super" first="l1" second="p2">Intersection between l1 and p2</Intersection>
<Line name="l3" n="11" hidden="super" from="P2" to="P3">Line through P2 and P3</Line>
<Midpoint name="M3" n="12" hidden="super" first="P2" second="P3">Midpoint between P2 and P3</Midpoint>
<Plumb name="p3" n="13" hidden="super" point="M3" line="l3" valid="true">Perpendicular line through M3 to l3</Plumb>
<Line name="l4" n="14" hidden="super" from="P2" to="I2">Line through P2 and I2</Line>
<Midpoint name="M4" n="15" hidden="super" first="P2" second="I2">Midpoint between P2 and I2</Midpoint>
<Plumb name="p4" n="16" hidden="super" point="M4" line="l4" valid="true">Perpendicular line through M4 to l4</Plumb>
<Intersection name="I3" n="17" hidden="super" first="p3" second="p4">Intersection between p3 and p4</Intersection>
<Circle name="c2" n="18" through="P2" midpoint="I3" start="I4" end="I5" acute="true">Circle around I3 through P2</Circle>
<Intersection name="I4" n="19" hidden="true" first="k" second="c2" shape="circle" which="second">Intersection between k and c2</Intersection>
<Intersection name="I5" n="20" hidden="true" first="c2" second="k" shape="circle" which="second">Intersection between c2 and k</Intersection>
<PointOn name="P4" n="21" on="k" inside="true" x="2.32544333052949" y="0.6774570734722207" shape="circle">Point on k</PointOn>
<Line name="l5" n="65" hidden="super" from="Mc" to="P2">Line through Mc and P2</Line>
<Midpoint name="M5" n="66" hidden="super" first="Mc" second="P2">Midpoint between Mc and P2</Midpoint>
<Plumb name="p5" n="67" hidden="super" point="M5" line="l5" valid="true">Perpendicular line through M5 to l5</Plumb>
<Intersection name="I6" n="68" hidden="super" first="p5" second="k" which="second">Intersection between p5 and k</Intersection>
<Line name="l6" n="69" hidden="super" from="Mc" to="I6">Line through Mc and I6</Line>
<Midpoint name="M6" n="70" hidden="super" first="Mc" second="I6">Midpoint between Mc and I6</Midpoint>
<Plumb name="p6" n="71" hidden="super" point="M6" line="l6" valid="true">Perpendicular line through M6 to l6</Plumb>
<Intersection name="I7" n="72" hidden="super" first="l5" second="p6">Intersection between l5 and p6</Intersection>
<Line name="l7" n="73" hidden="super" from="P2" to="P4">Line through P2 and P4</Line>
<Midpoint name="M7" n="74" hidden="super" first="P2" second="P4">Midpoint between P2 and P4</Midpoint>
<Plumb name="p7" n="75" hidden="super" point="M7" line="l7" valid="true">Perpendicular line through M7 to l7</Plumb>
<Line name="l8" n="76" hidden="super" from="P2" to="I7">Line through P2 and I7</Line>
<Midpoint name="M8" n="77" hidden="super" first="P2" second="I7">Midpoint between P2 and I7</Midpoint>
<Plumb name="p8" n="78" hidden="super" point="M8" line="l8" valid="true">Perpendicular line through M8 to l8</Plumb>
<Intersection name="I8" n="79" hidden="super" first="p7" second="p8">Intersection between p7 and p8</Intersection>
<Line name="l9" n="80" hidden="super" from="I8" to="P4">Line through I8 and P4</Line>
<Plumb name="p9" n="81" hidden="super" point="P4" line="l9" valid="true">Perpendicular line through P4 to l9</Plumb>
<Line name="l10" n="82" hidden="super" from="Mc" to="P2">Line through Mc and P2</Line>
<Intersection name="I9" n="83" hidden="super" first="p9" second="l10">Intersection between p9 and l10</Intersection>
<Circle name="c3" n="84" hidden="true" through="P4" midpoint="I9" acute="true">Circle around I9 through P4</Circle>
<Line name="l11" n="106" hidden="super" from="Mc" to="P3">Line through Mc and P3</Line>
<Midpoint name="M9" n="107" hidden="super" first="Mc" second="P3">Midpoint between Mc and P3</Midpoint>
<Plumb name="p10" n="108" hidden="super" point="M9" line="l11" valid="true">Perpendicular line through M9 to l11</Plumb>
<Intersection name="I10" n="109" hidden="super" first="p10" second="k" which="second">Intersection between p10 and k</Intersection>
<Line name="l12" n="110" hidden="super" from="Mc" to="I10">Line through Mc and I10</Line>
<Midpoint name="M10" n="111" hidden="super" first="Mc" second="I10">Midpoint between Mc and I10</Midpoint>
<Plumb name="p11" n="112" hidden="super" point="M10" line="l12" valid="true">Perpendicular line through M10 to l12</Plumb>
<Intersection name="I11" n="113" hidden="super" first="l11" second="p11">Intersection between l11 and p11</Intersection>
<Line name="l13" n="114" hidden="super" from="P3" to="P4">Line through P3 and P4</Line>
<Midpoint name="M11" n="115" hidden="super" first="P3" second="P4">Midpoint between P3 and P4</Midpoint>
<Plumb name="p12" n="116" hidden="super" point="M11" line="l13" valid="true">Perpendicular line through M11 to l13</Plumb>
<Line name="l14" n="117" hidden="super" from="P3" to="I11">Line through P3 and I11</Line>
<Midpoint name="M12" n="118" hidden="super" first="P3" second="I11">Midpoint between P3 and I11</Midpoint>
<Plumb name="p13" n="119" hidden="super" point="M12" line="l14" valid="true">Perpendicular line through M12 to l14</Plumb>
<Intersection name="I12" n="120" hidden="super" first="p12" second="p13">Intersection between p12 and p13</Intersection>
<Line name="l15" n="121" hidden="super" from="I12" to="P4">Line through I12 and P4</Line>
<Plumb name="p14" n="122" hidden="super" point="P4" line="l15" valid="true">Perpendicular line through P4 to l15</Plumb>
<Line name="l16" n="123" hidden="super" from="Mc" to="P3">Line through Mc and P3</Line>
<Intersection name="I13" n="124" hidden="super" first="p14" second="l16">Intersection between p14 and l16</Intersection>
<Circle name="c4" n="125" hidden="true" through="P4" midpoint="I13" acute="true">Circle around I13 through P4</Circle>
<Intersection name="I14" n="145" hidden="true" first="c3" second="c4" awayfrom="P4" shape="circle" which="first">Intersection between c3 and c4</Intersection>
<Line name="l17" n="146" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Midpoint name="M13" n="147" hidden="super" first="Mc" second="P4">Midpoint between Mc and P4</Midpoint>
<Plumb name="p15" n="148" hidden="super" point="M13" line="l17" valid="true">Perpendicular line through M13 to l17</Plumb>
<Intersection name="I16" n="149" hidden="super" first="p15" second="k" which="second">Intersection between p15 and k</Intersection>
<Line name="l18" n="150" hidden="super" from="Mc" to="I16">Line through Mc and I16</Line>
<Midpoint name="M14" n="151" hidden="super" first="Mc" second="I16">Midpoint between Mc and I16</Midpoint>
<Plumb name="p16" n="152" hidden="super" point="M14" line="l18" valid="true">Perpendicular line through M14 to l18</Plumb>
<Intersection name="I17" n="153" hidden="super" first="l17" second="p16">Intersection between l17 and p16</Intersection>
<Line name="l19" n="154" hidden="super" from="P4" to="I14">Line through P4 and I14</Line>
<Midpoint name="M15" n="155" hidden="super" first="P4" second="I14">Midpoint between P4 and I14</Midpoint>
<Plumb name="p17" n="156" hidden="super" point="M15" line="l19" valid="true">Perpendicular line through M15 to l19</Plumb>
<Line name="l20" n="157" hidden="super" from="P4" to="I17">Line through P4 and I17</Line>
<Midpoint name="M16" n="158" hidden="super" first="P4" second="I17">Midpoint between P4 and I17</Midpoint>
<Plumb name="p18" n="159" hidden="super" point="M16" line="l20" valid="true">Perpendicular line through M16 to l20</Plumb>
<Intersection name="I18" n="160" hidden="super" first="p17" second="p18">Intersection between p17 and p18</Intersection>
<Circle name="c5" n="161" through="P4" midpoint="I18" start="I19" end="I20" acute="true">Circle around I18 through P4</Circle>
<Intersection name="I19" n="162" hidden="true" first="k" second="c5" shape="circle" which="second">Intersection between k and c5</Intersection>
<Intersection name="I20" n="163" hidden="true" first="c5" second="k" shape="circle" which="second">Intersection between c5 and k</Intersection>
<PointOn name="P5" n="185" hidden="true" on="c5" alpha="2.7236239195711804" x="2.5519721830175497" y="1.2482237399566463" shape="circle">Point on c5</PointOn>
<Line name="l21" n="186" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Midpoint name="M17" n="187" hidden="super" first="Mc" second="P4">Midpoint between Mc and P4</Midpoint>
<Plumb name="p19" n="188" hidden="super" point="M17" line="l21" valid="true">Perpendicular line through M17 to l21</Plumb>
<Intersection name="I21" n="189" hidden="super" first="p19" second="k" which="second">Intersection between p19 and k</Intersection>
<Line name="l22" n="190" hidden="super" from="Mc" to="I21">Line through Mc and I21</Line>
<Midpoint name="M18" n="191" hidden="super" first="Mc" second="I21">Midpoint between Mc and I21</Midpoint>
<Plumb name="p20" n="192" hidden="super" point="M18" line="l22" valid="true">Perpendicular line through M18 to l22</Plumb>
<Intersection name="I22" n="193" hidden="super" first="l21" second="p20">Intersection between l21 and p20</Intersection>
<Line name="l23" n="194" hidden="super" from="P4" to="P5">Line through P4 and P5</Line>
<Midpoint name="M19" n="195" hidden="super" first="P4" second="P5">Midpoint between P4 and P5</Midpoint>
<Plumb name="p21" n="196" hidden="super" point="M19" line="l23" valid="true">Perpendicular line through M19 to l23</Plumb>
<Line name="l24" n="197" hidden="super" from="P4" to="I22">Line through P4 and I22</Line>
<Midpoint name="M20" n="198" hidden="super" first="P4" second="I22">Midpoint between P4 and I22</Midpoint>
<Plumb name="p22" n="199" hidden="super" point="M20" line="l24" valid="true">Perpendicular line through M20 to l24</Plumb>
<Intersection name="I23" n="200" hidden="super" first="p21" second="p22">Intersection between p21 and p22</Intersection>
<Line name="l25" n="201" hidden="super" from="I23" to="P5">Line through I23 and P5</Line>
<Plumb name="p23" n="202" hidden="super" point="P5" line="l25" valid="true">Perpendicular line through P5 to l25</Plumb>
<Line name="l26" n="203" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Intersection name="I24" n="204" hidden="super" first="p23" second="l26">Intersection between p23 and l26</Intersection>
<Circle name="c6" n="205" hidden="true" through="P5" midpoint="I24" acute="true">Circle around I24 through P5</Circle>
<Intersection name="I26" n="267" hidden="true" first="c5" second="c6" awayfrom="P5" shape="circle" which="second">Intersection between c5 and c6</Intersection>
<Line name="l27" n="268" hidden="super" from="Mc" to="I26">Line through Mc and I26</Line>
<Midpoint name="M21" n="269" hidden="super" first="Mc" second="I26">Midpoint between Mc and I26</Midpoint>
<Plumb name="p24" n="270" hidden="super" point="M21" line="l27" valid="true">Perpendicular line through M21 to l27</Plumb>
<Intersection name="I27" n="271" hidden="super" first="p24" second="k" which="second">Intersection between p24 and k</Intersection>
<Line name="l28" n="272" hidden="super" from="Mc" to="I27">Line through Mc and I27</Line>
<Midpoint name="M22" n="273" hidden="super" first="Mc" second="I27">Midpoint between Mc and I27</Midpoint>
<Plumb name="p25" n="274" hidden="super" point="M22" line="l28" valid="true">Perpendicular line through M22 to l28</Plumb>
<Intersection name="I28" n="275" hidden="super" first="l27" second="p25">Intersection between l27 and p25</Intersection>
<Line name="l29" n="276" hidden="super" from="I26" to="P5">Line through I26 and P5</Line>
<Midpoint name="M23" n="277" hidden="super" first="I26" second="P5">Midpoint between I26 and P5</Midpoint>
<Plumb name="p26" n="278" hidden="super" point="M23" line="l29" valid="true">Perpendicular line through M23 to l29</Plumb>
<Line name="l30" n="279" hidden="super" from="I26" to="I28">Line through I26 and I28</Line>
<Midpoint name="M24" n="280" hidden="super" first="I26" second="I28">Midpoint between I26 and I28</Midpoint>
<Plumb name="p27" n="281" hidden="super" point="M24" line="l30" valid="true">Perpendicular line through M24 to l30</Plumb>
<Intersection name="I29" n="282" hidden="super" first="p26" second="p27">Intersection between p26 and p27</Intersection>
<Line name="l31" n="283" hidden="super" from="I29" to="P5">Line through I29 and P5</Line>
<Plumb name="p28" n="284" hidden="super" point="P5" line="l31" valid="true">Perpendicular line through P5 to l31</Plumb>
<Line name="l32" n="285" hidden="super" from="Mc" to="I26">Line through Mc and I26</Line>
<Intersection name="I30" n="286" hidden="super" first="p28" second="l32">Intersection between p28 and l32</Intersection>
<Circle name="c7" n="287" hidden="super" through="P5" midpoint="I30" acute="true">Circle around I30 through P5</Circle>
<Line name="l33" n="288" hidden="super" from="Mc" to="P5">Line through Mc and P5</Line>
<Midpoint name="M25" n="289" hidden="super" first="Mc" second="P5">Midpoint between Mc and P5</Midpoint>
<Plumb name="p29" n="290" hidden="super" point="M25" line="l33" valid="true">Perpendicular line through M25 to l33</Plumb>
<Intersection name="I31" n="291" hidden="super" first="p29" second="k" which="second">Intersection between p29 and k</Intersection>
<Line name="l34" n="292" hidden="super" from="Mc" to="I31">Line through Mc and I31</Line>
<Midpoint name="M26" n="293" hidden="super" first="Mc" second="I31">Midpoint between Mc and I31</Midpoint>
<Plumb name="p30" n="294" hidden="super" point="M26" line="l34" valid="true">Perpendicular line through M26 to l34</Plumb>
<Intersection name="I32" n="295" hidden="super" first="l33" second="p30">Intersection between l33 and p30</Intersection>
<Line name="l35" n="296" hidden="super" from="P5" to="I26">Line through P5 and I26</Line>
<Midpoint name="M27" n="297" hidden="super" first="P5" second="I26">Midpoint between P5 and I26</Midpoint>
<Plumb name="p31" n="298" hidden="super" point="M27" line="l35" valid="true">Perpendicular line through M27 to l35</Plumb>
<Line name="l36" n="299" hidden="super" from="P5" to="I32">Line through P5 and I32</Line>
<Midpoint name="M28" n="300" hidden="super" first="P5" second="I32">Midpoint between P5 and I32</Midpoint>
<Plumb name="p32" n="301" hidden="super" point="M28" line="l36" valid="true">Perpendicular line through M28 to l36</Plumb>
<Intersection name="I33" n="302" hidden="super" first="p31" second="p32">Intersection between p31 and p32</Intersection>
<Line name="l37" n="303" hidden="super" from="I33" to="I26">Line through I33 and I26</Line>
<Plumb name="p33" n="304" hidden="super" point="I26" line="l37" valid="true">Perpendicular line through I26 to l37</Plumb>
<Line name="l38" n="305" hidden="super" from="Mc" to="P5">Line through Mc and P5</Line>
<Intersection name="I34" n="306" hidden="super" first="p33" second="l38">Intersection between p33 and l38</Intersection>
<Circle name="c8" n="307" hidden="super" through="I26" midpoint="I34" acute="true">Circle around I34 through I26</Circle>
<Intersection name="I35" n="308" hidden="super" first="c7" second="c8" which="first">Intersection between c7 and c8</Intersection>
<Intersection name="I36" n="309" hidden="super" first="c7" second="c8" which="second">Intersection between c7 and c8</Intersection>
<Line name="l39" n="310" hidden="super" from="Mc" to="I36">Line through Mc and I36</Line>
<Midpoint name="M29" n="311" hidden="super" first="Mc" second="I36">Midpoint between Mc and I36</Midpoint>
<Plumb name="p34" n="312" hidden="super" point="M29" line="l39" valid="true">Perpendicular line through M29 to l39</Plumb>
<Intersection name="I37" n="313" hidden="super" first="p34" second="k" which="second">Intersection between p34 and k</Intersection>
<Line name="l40" n="314" hidden="super" from="Mc" to="I37">Line through Mc and I37</Line>
<Midpoint name="M30" n="315" hidden="super" first="Mc" second="I37">Midpoint between Mc and I37</Midpoint>
<Plumb name="p35" n="316" hidden="super" point="M30" line="l40" valid="true">Perpendicular line through M30 to l40</Plumb>
<Intersection name="I38" n="317" hidden="super" first="l39" second="p35">Intersection between l39 and p35</Intersection>
<Line name="l41" n="318" hidden="super" from="I36" to="I35">Line through I36 and I35</Line>
<Midpoint name="M31" n="319" hidden="super" first="I36" second="I35">Midpoint between I36 and I35</Midpoint>
<Plumb name="p36" n="320" hidden="super" point="M31" line="l41" valid="true">Perpendicular line through M31 to l41</Plumb>
<Line name="l42" n="321" hidden="super" from="I36" to="I38">Line through I36 and I38</Line>
<Midpoint name="M32" n="322" hidden="super" first="I36" second="I38">Midpoint between I36 and I38</Midpoint>
<Plumb name="p37" n="323" hidden="super" point="M32" line="l42" valid="true">Perpendicular line through M32 to l42</Plumb>
<Intersection name="I39" n="324" hidden="super" first="p36" second="p37">Intersection between p36 and p37</Intersection>
<Circle name="c9" n="325" through="I36" midpoint="I39" start="I41" end="I40" acute="true">Circle around I39 through I36</Circle>
<Intersection name="I40" n="326" hidden="true" first="c9" second="k" shape="circle" which="first">Intersection between c9 and k</Intersection>
<Intersection name="I41" n="327" hidden="true" first="k" second="c9" shape="circle" which="first">Intersection between k and c9</Intersection>
<PointOn name="P6" n="329" on="k" inside="true" alpha="1.414624156327935" x="3.1114823649251857" y="-2.1020274983012674" shape="circle">Point on k</PointOn>
<Line name="l43" n="352" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Midpoint name="M33" n="353" hidden="super" first="Mc" second="P4">Midpoint between Mc and P4</Midpoint>
<Plumb name="p38" n="354" hidden="super" point="M33" line="l43" valid="true">Perpendicular line through M33 to l43</Plumb>
<Intersection name="I42" n="355" hidden="super" first="p38" second="k" which="second">Intersection between p38 and k</Intersection>
<Line name="l44" n="356" hidden="super" from="Mc" to="I42">Line through Mc and I42</Line>
<Midpoint name="M34" n="357" hidden="super" first="Mc" second="I42">Midpoint between Mc and I42</Midpoint>
<Plumb name="p39" n="358" hidden="super" point="M34" line="l44" valid="true">Perpendicular line through M34 to l44</Plumb>
<Intersection name="I43" n="359" hidden="super" first="l43" second="p39">Intersection between l43 and p39</Intersection>
<Line name="l45" n="360" hidden="super" from="P4" to="P6">Line through P4 and P6</Line>
<Midpoint name="M35" n="361" hidden="super" first="P4" second="P6">Midpoint between P4 and P6</Midpoint>
<Plumb name="p40" n="362" hidden="super" point="M35" line="l45" valid="true">Perpendicular line through M35 to l45</Plumb>
<Line name="l46" n="363" hidden="super" from="P4" to="I43">Line through P4 and I43</Line>
<Midpoint name="M36" n="364" hidden="super" first="P4" second="I43">Midpoint between P4 and I43</Midpoint>
<Plumb name="p41" n="365" hidden="super" point="M36" line="l46" valid="true">Perpendicular line through M36 to l46</Plumb>
<Intersection name="I44" n="366" hidden="super" first="p40" second="p41">Intersection between p40 and p41</Intersection>
<Line name="l47" n="367" hidden="super" from="I44" to="P6">Line through I44 and P6</Line>
<Plumb name="p42" n="368" hidden="super" point="P6" line="l47" valid="true">Perpendicular line through P6 to l47</Plumb>
<Line name="l48" n="369" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Intersection name="I45" n="370" hidden="super" first="p42" second="l48">Intersection between p42 and l48</Intersection>
<Circle name="c10" n="371" hidden="true" through="P6" midpoint="I45" acute="true">Circle around I45 through P6</Circle>
<PointOn name="P7" n="372" hidden="true" on="c9" alpha="4.4947636937339315" x="3.558662296086122" y="0.32597972359475413" shape="circle">Point on c9</PointOn>
<Line name="l49" n="394" hidden="super" from="Mc" to="P7">Line through Mc and P7</Line>
<Midpoint name="M37" n="395" hidden="super" first="Mc" second="P7">Midpoint between Mc and P7</Midpoint>
<Plumb name="p43" n="396" hidden="super" point="M37" line="l49" valid="true">Perpendicular line through M37 to l49</Plumb>
<Intersection name="I46" n="397" hidden="super" first="p43" second="k" which="second">Intersection between p43 and k</Intersection>
<Line name="l50" n="398" hidden="super" from="Mc" to="I46">Line through Mc and I46</Line>
<Midpoint name="M38" n="399" hidden="super" first="Mc" second="I46">Midpoint between Mc and I46</Midpoint>
<Plumb name="p44" n="400" hidden="super" point="M38" line="l50" valid="true">Perpendicular line through M38 to l50</Plumb>
<Intersection name="I47" n="401" hidden="super" first="l49" second="p44">Intersection between l49 and p44</Intersection>
<Line name="l51" n="402" hidden="super" from="P7" to="P6">Line through P7 and P6</Line>
<Midpoint name="M39" n="403" hidden="super" first="P7" second="P6">Midpoint between P7 and P6</Midpoint>
<Plumb name="p45" n="404" hidden="super" point="M39" line="l51" valid="true">Perpendicular line through M39 to l51</Plumb>
<Line name="l52" n="405" hidden="super" from="P7" to="I47">Line through P7 and I47</Line>
<Midpoint name="M40" n="406" hidden="super" first="P7" second="I47">Midpoint between P7 and I47</Midpoint>
<Plumb name="p46" n="407" hidden="super" point="M40" line="l52" valid="true">Perpendicular line through M40 to l52</Plumb>
<Intersection name="I48" n="408" hidden="super" first="p45" second="p46">Intersection between p45 and p46</Intersection>
<Line name="l53" n="409" hidden="super" from="I48" to="P6">Line through I48 and P6</Line>
<Plumb name="p47" n="410" hidden="super" point="P6" line="l53" valid="true">Perpendicular line through P6 to l53</Plumb>
<Line name="l54" n="411" hidden="super" from="Mc" to="P7">Line through Mc and P7</Line>
<Intersection name="I49" n="412" hidden="super" first="p47" second="l54">Intersection between p47 and l54</Intersection>
<Circle name="c11" n="413" hidden="true" through="P6" midpoint="I49" acute="true">Circle around I49 through P6</Circle>
<Intersection name="I50" n="433" hidden="true" first="c11" second="c10" awayfrom="P6" shape="circle" which="first">Intersection between c11 and c10</Intersection>
<Line name="l55" n="434" hidden="super" from="Mc" to="P6">Line through Mc and P6</Line>
<Midpoint name="M41" n="435" hidden="super" first="Mc" second="P6">Midpoint between Mc and P6</Midpoint>
<Plumb name="p48" n="436" hidden="super" point="M41" line="l55" valid="true">Perpendicular line through M41 to l55</Plumb>
<Intersection name="I52" n="437" hidden="super" first="p48" second="k" which="second">Intersection between p48 and k</Intersection>
<Line name="l56" n="438" hidden="super" from="Mc" to="I52">Line through Mc and I52</Line>
<Midpoint name="M42" n="439" hidden="super" first="Mc" second="I52">Midpoint between Mc and I52</Midpoint>
<Plumb name="p49" n="440" hidden="super" point="M42" line="l56" valid="true">Perpendicular line through M42 to l56</Plumb>
<Intersection name="I53" n="441" hidden="super" first="l55" second="p49">Intersection between l55 and p49</Intersection>
<Line name="l57" n="442" hidden="super" from="P6" to="I50">Line through P6 and I50</Line>
<Midpoint name="M43" n="443" hidden="super" first="P6" second="I50">Midpoint between P6 and I50</Midpoint>
<Plumb name="p50" n="444" hidden="super" point="M43" line="l57" valid="true">Perpendicular line through M43 to l57</Plumb>
<Line name="l58" n="445" hidden="super" from="P6" to="I53">Line through P6 and I53</Line>
<Midpoint name="M44" n="446" hidden="super" first="P6" second="I53">Midpoint between P6 and I53</Midpoint>
<Plumb name="p51" n="447" hidden="super" point="M44" line="l58" valid="true">Perpendicular line through M44 to l58</Plumb>
<Intersection name="I54" n="448" hidden="super" first="p50" second="p51">Intersection between p50 and p51</Intersection>
<Circle name="c12" n="449" through="P6" midpoint="I54" start="I55" end="I56" acute="true">Circle around I54 through P6</Circle>
<Intersection name="I55" n="450" hidden="true" first="k" second="c12" shape="circle" which="second">Intersection between k and c12</Intersection>
<Intersection name="I56" n="451" hidden="true" first="c12" second="k" shape="circle" which="second">Intersection between c12 and k</Intersection>
<Intersection name="I58" n="452" first="c2" second="c5" shape="circle" which="second">Intersection between c2 and c5</Intersection>
<Line name="l59" n="686" hidden="super" from="Mc" to="I58">Line through Mc and I58</Line>
<Midpoint name="M45" n="687" hidden="super" first="Mc" second="I58">Midpoint between Mc and I58</Midpoint>
<Plumb name="p52" n="688" hidden="super" point="M45" line="l59" valid="true">Perpendicular line through M45 to l59</Plumb>
<Intersection name="I59" n="689" hidden="super" first="p52" second="k" which="second">Intersection between p52 and k</Intersection>
<Line name="l60" n="690" hidden="super" from="Mc" to="I59">Line through Mc and I59</Line>
<Midpoint name="M46" n="691" hidden="super" first="Mc" second="I59">Midpoint between Mc and I59</Midpoint>
<Plumb name="p53" n="692" hidden="super" point="M46" line="l60" valid="true">Perpendicular line through M46 to l60</Plumb>
<Intersection name="I60" n="693" hidden="super" first="l59" second="p53">Intersection between l59 and p53</Intersection>
<Line name="l61" n="694" hidden="super" from="I58" to="P4">Line through I58 and P4</Line>
<Midpoint name="M47" n="695" hidden="super" first="I58" second="P4">Midpoint between I58 and P4</Midpoint>
<Plumb name="p54" n="696" hidden="super" point="M47" line="l61" valid="true">Perpendicular line through M47 to l61</Plumb>
<Line name="l62" n="697" hidden="super" from="I58" to="I60">Line through I58 and I60</Line>
<Midpoint name="M48" n="698" hidden="super" first="I58" second="I60">Midpoint between I58 and I60</Midpoint>
<Plumb name="p55" n="699" hidden="super" point="M48" line="l62" valid="true">Perpendicular line through M48 to l62</Plumb>
<Intersection name="I61" n="700" hidden="super" first="p54" second="p55">Intersection between p54 and p55</Intersection>
<Circle name="c13" n="701" hidden="super" through="I58" midpoint="I61" acute="true">Circle around I61 through I58</Circle>
<Line name="l63" n="702" hidden="super" from="Mc" to="I61">Line through Mc and I61</Line>
<Intersection name="I62" n="703" hidden="super" first="l63" second="c13" closeto="Mc" which="second">Intersection between l63 and c13</Intersection>
<Line name="l64" n="704" hidden="super" from="Mc" to="I58">Line through Mc and I58</Line>
<Midpoint name="M49" n="705" hidden="super" first="Mc" second="I58">Midpoint between Mc and I58</Midpoint>
<Plumb name="p56" n="706" hidden="super" point="M49" line="l64" valid="true">Perpendicular line through M49 to l64</Plumb>
<Intersection name="I63" n="707" hidden="super" first="p56" second="k" which="second">Intersection between p56 and k</Intersection>
<Line name="l65" n="708" hidden="super" from="Mc" to="I63">Line through Mc and I63</Line>
<Midpoint name="M50" n="709" hidden="super" first="Mc" second="I63">Midpoint between Mc and I63</Midpoint>
<Plumb name="p57" n="710" hidden="super" point="M50" line="l65" valid="true">Perpendicular line through M50 to l65</Plumb>
<Intersection name="I64" n="711" hidden="super" first="l64" second="p57">Intersection between l64 and p57</Intersection>
<Line name="l66" n="712" hidden="super" from="I58" to="I62">Line through I58 and I62</Line>
<Midpoint name="M51" n="713" hidden="super" first="I58" second="I62">Midpoint between I58 and I62</Midpoint>
<Plumb name="p58" n="714" hidden="super" point="M51" line="l66" valid="true">Perpendicular line through M51 to l66</Plumb>
<Line name="l67" n="715" hidden="super" from="I58" to="I64">Line through I58 and I64</Line>
<Midpoint name="M52" n="716" hidden="super" first="I58" second="I64">Midpoint between I58 and I64</Midpoint>
<Plumb name="p59" n="717" hidden="super" point="M52" line="l67" valid="true">Perpendicular line through M52 to l67</Plumb>
<Intersection name="I65" n="718" hidden="super" first="p58" second="p59">Intersection between p58 and p59</Intersection>
<Line name="l68" n="719" hidden="super" from="I65" to="I62">Line through I65 and I62</Line>
<Plumb name="p60" n="720" hidden="super" point="I62" line="l68" valid="true">Perpendicular line through I62 to l68</Plumb>
<Line name="l69" n="721" hidden="super" from="Mc" to="I58">Line through Mc and I58</Line>
<Intersection name="I66" n="722" hidden="super" first="p60" second="l69">Intersection between p60 and l69</Intersection>
<Circle name="c14" n="723" hidden="super" through="I62" midpoint="I66" acute="true">Circle around I66 through I62</Circle>
<Intersection name="I67" n="724" hidden="super" first="c13" second="c14" which="first">Intersection between c13 and c14</Intersection>
<Intersection name="I68" n="725" hidden="super" first="c13" second="c14" which="second">Intersection between c13 and c14</Intersection>
<Line name="l70" n="726" hidden="super" from="Mc" to="I68">Line through Mc and I68</Line>
<Midpoint name="M53" n="727" hidden="super" first="Mc" second="I68">Midpoint between Mc and I68</Midpoint>
<Plumb name="p61" n="728" hidden="super" point="M53" line="l70" valid="true">Perpendicular line through M53 to l70</Plumb>
<Intersection name="I69" n="729" hidden="super" first="p61" second="k" which="second">Intersection between p61 and k</Intersection>
<Line name="l71" n="730" hidden="super" from="Mc" to="I69">Line through Mc and I69</Line>
<Midpoint name="M54" n="731" hidden="super" first="Mc" second="I69">Midpoint between Mc and I69</Midpoint>
<Plumb name="p62" n="732" hidden="super" point="M54" line="l71" valid="true">Perpendicular line through M54 to l71</Plumb>
<Intersection name="I70" n="733" hidden="super" first="l70" second="p62">Intersection between l70 and p62</Intersection>
<Line name="l72" n="734" hidden="super" from="I68" to="I67">Line through I68 and I67</Line>
<Midpoint name="M55" n="735" hidden="super" first="I68" second="I67">Midpoint between I68 and I67</Midpoint>
<Plumb name="p63" n="736" hidden="super" point="M55" line="l72" valid="true">Perpendicular line through M55 to l72</Plumb>
<Line name="l73" n="737" hidden="super" from="I68" to="I70">Line through I68 and I70</Line>
<Midpoint name="M56" n="738" hidden="super" first="I68" second="I70">Midpoint between I68 and I70</Midpoint>
<Plumb name="p64" n="739" hidden="super" point="M56" line="l73" valid="true">Perpendicular line through M56 to l73</Plumb>
<Intersection name="I71" n="740" hidden="super" first="p63" second="p64">Intersection between p63 and p64</Intersection>
<Line name="l74" n="741" hidden="super" from="I71" to="I67">Line through I71 and I67</Line>
<Plumb name="p65" n="742" hidden="super" point="I67" line="l74" valid="true">Perpendicular line through I67 to l74</Plumb>
<Line name="l75" n="743" hidden="super" from="Mc" to="I68">Line through Mc and I68</Line>
<Intersection name="I72" n="744" hidden="super" first="p65" second="l75">Intersection between p65 and l75</Intersection>
<Circle name="c15" n="745" hidden="super" through="I67" midpoint="I72" acute="true">Circle around I72 through I67</Circle>
<Line name="l76" n="746" hidden="super" from="Mc" to="I67">Line through Mc and I67</Line>
<Midpoint name="M57" n="747" hidden="super" first="Mc" second="I67">Midpoint between Mc and I67</Midpoint>
<Plumb name="p66" n="748" hidden="super" point="M57" line="l76" valid="true">Perpendicular line through M57 to l76</Plumb>
<Intersection name="I73" n="749" hidden="super" first="p66" second="k" which="second">Intersection between p66 and k</Intersection>
<Line name="l77" n="750" hidden="super" from="Mc" to="I73">Line through Mc and I73</Line>
<Midpoint name="M58" n="751" hidden="super" first="Mc" second="I73">Midpoint between Mc and I73</Midpoint>
<Plumb name="p67" n="752" hidden="super" point="M58" line="l77" valid="true">Perpendicular line through M58 to l77</Plumb>
<Intersection name="I74" n="753" hidden="super" first="l76" second="p67">Intersection between l76 and p67</Intersection>
<Line name="l78" n="754" hidden="super" from="I67" to="I68">Line through I67 and I68</Line>
<Midpoint name="M59" n="755" hidden="super" first="I67" second="I68">Midpoint between I67 and I68</Midpoint>
<Plumb name="p68" n="756" hidden="super" point="M59" line="l78" valid="true">Perpendicular line through M59 to l78</Plumb>
<Line name="l79" n="757" hidden="super" from="I67" to="I74">Line through I67 and I74</Line>
<Midpoint name="M60" n="758" hidden="super" first="I67" second="I74">Midpoint between I67 and I74</Midpoint>
<Plumb name="p69" n="759" hidden="super" point="M60" line="l79" valid="true">Perpendicular line through M60 to l79</Plumb>
<Intersection name="I75" n="760" hidden="super" first="p68" second="p69">Intersection between p68 and p69</Intersection>
<Line name="l80" n="761" hidden="super" from="I75" to="I68">Line through I75 and I68</Line>
<Plumb name="p70" n="762" hidden="super" point="I68" line="l80" valid="true">Perpendicular line through I68 to l80</Plumb>
<Line name="l81" n="763" hidden="super" from="Mc" to="I67">Line through Mc and I67</Line>
<Intersection name="I76" n="764" hidden="super" first="p70" second="l81">Intersection between p70 and l81</Intersection>
<Circle name="c16" n="765" hidden="super" through="I68" midpoint="I76" acute="true">Circle around I76 through I68</Circle>
<Intersection name="I77" n="766" hidden="super" first="c15" second="c16" which="first">Intersection between c15 and c16</Intersection>
<Intersection name="I78" n="767" hidden="super" first="c15" second="c16" which="second">Intersection between c15 and c16</Intersection>
<Line name="l82" n="768" hidden="super" from="Mc" to="I78">Line through Mc and I78</Line>
<Midpoint name="M61" n="769" hidden="super" first="Mc" second="I78">Midpoint between Mc and I78</Midpoint>
<Plumb name="p71" n="770" hidden="super" point="M61" line="l82" valid="true">Perpendicular line through M61 to l82</Plumb>
<Intersection name="I79" n="771" hidden="super" first="p71" second="k" which="second">Intersection between p71 and k</Intersection>
<Line name="l83" n="772" hidden="super" from="Mc" to="I79">Line through Mc and I79</Line>
<Midpoint name="M62" n="773" hidden="super" first="Mc" second="I79">Midpoint between Mc and I79</Midpoint>
<Plumb name="p72" n="774" hidden="super" point="M62" line="l83" valid="true">Perpendicular line through M62 to l83</Plumb>
<Intersection name="I80" n="775" hidden="super" first="l82" second="p72">Intersection between l82 and p72</Intersection>
<Line name="l84" n="776" hidden="super" from="I78" to="I77">Line through I78 and I77</Line>
<Midpoint name="M63" n="777" hidden="super" first="I78" second="I77">Midpoint between I78 and I77</Midpoint>
<Plumb name="p73" n="778" hidden="super" point="M63" line="l84" valid="true">Perpendicular line through M63 to l84</Plumb>
<Line name="l85" n="779" hidden="super" from="I78" to="I80">Line through I78 and I80</Line>
<Midpoint name="M64" n="780" hidden="super" first="I78" second="I80">Midpoint between I78 and I80</Midpoint>
<Plumb name="p74" n="781" hidden="super" point="M64" line="l85" valid="true">Perpendicular line through M64 to l85</Plumb>
<Intersection name="I81" n="782" hidden="super" first="p73" second="p74">Intersection between p73 and p74</Intersection>
<Circle name="c17" n="783" hidden="super" through="I78" midpoint="I81" acute="true">Circle around I81 through I78</Circle>
<Line name="l86" n="784" hidden="super" from="Mc" to="I58">Line through Mc and I58</Line>
<Midpoint name="M65" n="785" hidden="super" first="Mc" second="I58">Midpoint between Mc and I58</Midpoint>
<Plumb name="p75" n="786" hidden="super" point="M65" line="l86" valid="true">Perpendicular line through M65 to l86</Plumb>
<Intersection name="I82" n="787" hidden="super" first="p75" second="k" which="second">Intersection between p75 and k</Intersection>
<Line name="l87" n="788" hidden="super" from="Mc" to="I82">Line through Mc and I82</Line>
<Midpoint name="M66" n="789" hidden="super" first="Mc" second="I82">Midpoint between Mc and I82</Midpoint>
<Plumb name="p76" n="790" hidden="super" point="M66" line="l87" valid="true">Perpendicular line through M66 to l87</Plumb>
<Intersection name="I83" n="791" hidden="super" first="l86" second="p76">Intersection between l86 and p76</Intersection>
<Line name="l88" n="792" hidden="super" from="I58" to="P6">Line through I58 and P6</Line>
<Midpoint name="M67" n="793" hidden="super" first="I58" second="P6">Midpoint between I58 and P6</Midpoint>
<Plumb name="p77" n="794" hidden="super" point="M67" line="l88" valid="true">Perpendicular line through M67 to l88</Plumb>
<Line name="l89" n="795" hidden="super" from="I58" to="I83">Line through I58 and I83</Line>
<Midpoint name="M68" n="796" hidden="super" first="I58" second="I83">Midpoint between I58 and I83</Midpoint>
<Plumb name="p78" n="797" hidden="super" point="M68" line="l89" valid="true">Perpendicular line through M68 to l89</Plumb>
<Intersection name="I84" n="798" hidden="super" first="p77" second="p78">Intersection between p77 and p78</Intersection>
<Line name="l90" n="799" hidden="super" from="I84" to="P6">Line through I84 and P6</Line>
<Plumb name="p79" n="800" hidden="super" point="P6" line="l90" valid="true">Perpendicular line through P6 to l90</Plumb>
<Line name="l91" n="801" hidden="super" from="Mc" to="I58">Line through Mc and I58</Line>
<Intersection name="I85" n="802" hidden="super" first="p79" second="l91">Intersection between p79 and l91</Intersection>
<Circle name="c18" n="803" hidden="super" through="P6" midpoint="I85" acute="true">Circle around I85 through P6</Circle>
<Intersection name="I86" n="804" hidden="super" first="c18" second="c17" which="second">Intersection between c18 and c17</Intersection>
<Intersection name="I87" n="805" hidden="super" first="k" second="c13" which="first">Intersection between k and c13</Intersection>
<Intersection name="I88" n="806" hidden="super" first="k" second="c13" which="second">Intersection between k and c13</Intersection>
<Line name="l92" n="807" hidden="super" from="I88" to="I87">Line through I88 and I87</Line>
<Midpoint name="M69" n="808" hidden="super" first="I88" second="I87">Midpoint between I88 and I87</Midpoint>
<Plumb name="p80" n="809" hidden="super" point="M69" line="l92" valid="true">Perpendicular line through M69 to l92</Plumb>
<Line name="l93" n="810" hidden="super" from="I88" to="I86">Line through I88 and I86</Line>
<Midpoint name="M70" n="811" hidden="super" first="I88" second="I86">Midpoint between I88 and I86</Midpoint>
<Plumb name="p81" n="812" hidden="super" point="M70" line="l93" valid="true">Perpendicular line through M70 to l93</Plumb>
<Intersection name="I89" n="813" hidden="super" first="p80" second="p81">Intersection between p80 and p81</Intersection>
<Circle name="c19" n="814" hidden="super" through="I88" midpoint="I89" acute="true">Circle around I89 through I88</Circle>
<Line name="l94" n="815" hidden="super" from="Mc" to="I61">Line through Mc and I61</Line>
<Intersection name="I90" n="816" hidden="super" first="l94" second="c13" closeto="Mc" which="second">Intersection between l94 and c13</Intersection>
<Line name="l95" n="817" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Midpoint name="M71" n="818" hidden="super" first="Mc" second="P4">Midpoint between Mc and P4</Midpoint>
<Plumb name="p82" n="819" hidden="super" point="M71" line="l95" valid="true">Perpendicular line through M71 to l95</Plumb>
<Intersection name="I91" n="820" hidden="super" first="p82" second="k" which="second">Intersection between p82 and k</Intersection>
<Line name="l96" n="821" hidden="super" from="Mc" to="I91">Line through Mc and I91</Line>
<Midpoint name="M72" n="822" hidden="super" first="Mc" second="I91">Midpoint between Mc and I91</Midpoint>
<Plumb name="p83" n="823" hidden="super" point="M72" line="l96" valid="true">Perpendicular line through M72 to l96</Plumb>
<Intersection name="I92" n="824" hidden="super" first="l95" second="p83">Intersection between l95 and p83</Intersection>
<Line name="l97" n="825" hidden="super" from="P4" to="I90">Line through P4 and I90</Line>
<Midpoint name="M73" n="826" hidden="super" first="P4" second="I90">Midpoint between P4 and I90</Midpoint>
<Plumb name="p84" n="827" hidden="super" point="M73" line="l97" valid="true">Perpendicular line through M73 to l97</Plumb>
<Line name="l98" n="828" hidden="super" from="P4" to="I92">Line through P4 and I92</Line>
<Midpoint name="M74" n="829" hidden="super" first="P4" second="I92">Midpoint between P4 and I92</Midpoint>
<Plumb name="p85" n="830" hidden="super" point="M74" line="l98" valid="true">Perpendicular line through M74 to l98</Plumb>
<Intersection name="I93" n="831" hidden="super" first="p84" second="p85">Intersection between p84 and p85</Intersection>
<Line name="l99" n="832" hidden="super" from="I93" to="I90">Line through I93 and I90</Line>
<Plumb name="p86" n="833" hidden="super" point="I90" line="l99" valid="true">Perpendicular line through I90 to l99</Plumb>
<Line name="l100" n="834" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Intersection name="I94" n="835" hidden="super" first="p86" second="l100">Intersection between p86 and l100</Intersection>
<Circle name="c20" n="836" hidden="super" through="I90" midpoint="I94" acute="true">Circle around I94 through I90</Circle>
<Intersection name="I95" n="837" hidden="super" first="c13" second="c20" which="first">Intersection between c13 and c20</Intersection>
<Intersection name="I96" n="838" hidden="super" first="c13" second="c20" which="second">Intersection between c13 and c20</Intersection>
<Line name="l101" n="839" hidden="super" from="Mc" to="I96">Line through Mc and I96</Line>
<Midpoint name="M75" n="840" hidden="super" first="Mc" second="I96">Midpoint between Mc and I96</Midpoint>
<Plumb name="p87" n="841" hidden="super" point="M75" line="l101" valid="true">Perpendicular line through M75 to l101</Plumb>
<Intersection name="I97" n="842" hidden="super" first="p87" second="k" which="second">Intersection between p87 and k</Intersection>
<Line name="l102" n="843" hidden="super" from="Mc" to="I97">Line through Mc and I97</Line>
<Midpoint name="M76" n="844" hidden="super" first="Mc" second="I97">Midpoint between Mc and I97</Midpoint>
<Plumb name="p88" n="845" hidden="super" point="M76" line="l102" valid="true">Perpendicular line through M76 to l102</Plumb>
<Intersection name="I98" n="846" hidden="super" first="l101" second="p88">Intersection between l101 and p88</Intersection>
<Line name="l103" n="847" hidden="super" from="I96" to="I95">Line through I96 and I95</Line>
<Midpoint name="M77" n="848" hidden="super" first="I96" second="I95">Midpoint between I96 and I95</Midpoint>
<Plumb name="p89" n="849" hidden="super" point="M77" line="l103" valid="true">Perpendicular line through M77 to l103</Plumb>
<Line name="l104" n="850" hidden="super" from="I96" to="I98">Line through I96 and I98</Line>
<Midpoint name="M78" n="851" hidden="super" first="I96" second="I98">Midpoint between I96 and I98</Midpoint>
<Plumb name="p90" n="852" hidden="super" point="M78" line="l104" valid="true">Perpendicular line through M78 to l104</Plumb>
<Intersection name="I99" n="853" hidden="super" first="p89" second="p90">Intersection between p89 and p90</Intersection>
<Line name="l105" n="854" hidden="super" from="I99" to="I95">Line through I99 and I95</Line>
<Plumb name="p91" n="855" hidden="super" point="I95" line="l105" valid="true">Perpendicular line through I95 to l105</Plumb>
<Line name="l106" n="856" hidden="super" from="Mc" to="I96">Line through Mc and I96</Line>
<Intersection name="I100" n="857" hidden="super" first="p91" second="l106">Intersection between p91 and l106</Intersection>
<Circle name="c21" n="858" hidden="super" through="I95" midpoint="I100" acute="true">Circle around I100 through I95</Circle>
<Line name="l107" n="859" hidden="super" from="Mc" to="I95">Line through Mc and I95</Line>
<Midpoint name="M79" n="860" hidden="super" first="Mc" second="I95">Midpoint between Mc and I95</Midpoint>
<Plumb name="p92" n="861" hidden="super" point="M79" line="l107" valid="true">Perpendicular line through M79 to l107</Plumb>
<Intersection name="I101" n="862" hidden="super" first="p92" second="k" which="second">Intersection between p92 and k</Intersection>
<Line name="l108" n="863" hidden="super" from="Mc" to="I101">Line through Mc and I101</Line>
<Midpoint name="M80" n="864" hidden="super" first="Mc" second="I101">Midpoint between Mc and I101</Midpoint>
<Plumb name="p93" n="865" hidden="super" point="M80" line="l108" valid="true">Perpendicular line through M80 to l108</Plumb>
<Intersection name="I102" n="866" hidden="super" first="l107" second="p93">Intersection between l107 and p93</Intersection>
<Line name="l109" n="867" hidden="super" from="I95" to="I96">Line through I95 and I96</Line>
<Midpoint name="M81" n="868" hidden="super" first="I95" second="I96">Midpoint between I95 and I96</Midpoint>
<Plumb name="p94" n="869" hidden="super" point="M81" line="l109" valid="true">Perpendicular line through M81 to l109</Plumb>
<Line name="l110" n="870" hidden="super" from="I95" to="I102">Line through I95 and I102</Line>
<Midpoint name="M82" n="871" hidden="super" first="I95" second="I102">Midpoint between I95 and I102</Midpoint>
<Plumb name="p95" n="872" hidden="super" point="M82" line="l110" valid="true">Perpendicular line through M82 to l110</Plumb>
<Intersection name="I103" n="873" hidden="super" first="p94" second="p95">Intersection between p94 and p95</Intersection>
<Line name="l111" n="874" hidden="super" from="I103" to="I96">Line through I103 and I96</Line>
<Plumb name="p96" n="875" hidden="super" point="I96" line="l111" valid="true">Perpendicular line through I96 to l111</Plumb>
<Line name="l112" n="876" hidden="super" from="Mc" to="I95">Line through Mc and I95</Line>
<Intersection name="I104" n="877" hidden="super" first="p96" second="l112">Intersection between p96 and l112</Intersection>
<Circle name="c22" n="878" hidden="super" through="I96" midpoint="I104" acute="true">Circle around I104 through I96</Circle>
<Intersection name="I105" n="879" hidden="super" first="c21" second="c22" which="first">Intersection between c21 and c22</Intersection>
<Intersection name="I106" n="880" hidden="super" first="c21" second="c22" which="second">Intersection between c21 and c22</Intersection>
<Line name="l113" n="881" hidden="super" from="Mc" to="I106">Line through Mc and I106</Line>
<Midpoint name="M83" n="882" hidden="super" first="Mc" second="I106">Midpoint between Mc and I106</Midpoint>
<Plumb name="p97" n="883" hidden="super" point="M83" line="l113" valid="true">Perpendicular line through M83 to l113</Plumb>
<Intersection name="I107" n="884" hidden="super" first="p97" second="k" which="second">Intersection between p97 and k</Intersection>
<Line name="l114" n="885" hidden="super" from="Mc" to="I107">Line through Mc and I107</Line>
<Midpoint name="M84" n="886" hidden="super" first="Mc" second="I107">Midpoint between Mc and I107</Midpoint>
<Plumb name="p98" n="887" hidden="super" point="M84" line="l114" valid="true">Perpendicular line through M84 to l114</Plumb>
<Intersection name="I108" n="888" hidden="super" first="l113" second="p98">Intersection between l113 and p98</Intersection>
<Line name="l115" n="889" hidden="super" from="I106" to="I105">Line through I106 and I105</Line>
<Midpoint name="M85" n="890" hidden="super" first="I106" second="I105">Midpoint between I106 and I105</Midpoint>
<Plumb name="p99" n="891" hidden="super" point="M85" line="l115" valid="true">Perpendicular line through M85 to l115</Plumb>
<Line name="l116" n="892" hidden="super" from="I106" to="I108">Line through I106 and I108</Line>
<Midpoint name="M86" n="893" hidden="super" first="I106" second="I108">Midpoint between I106 and I108</Midpoint>
<Plumb name="p100" n="894" hidden="super" point="M86" line="l116" valid="true">Perpendicular line through M86 to l116</Plumb>
<Intersection name="I109" n="895" hidden="super" first="p99" second="p100">Intersection between p99 and p100</Intersection>
<Circle name="c23" n="896" hidden="super" through="I106" midpoint="I109" acute="true">Circle around I109 through I106</Circle>
<Intersection name="I110" n="897" hidden="super" first="c23" second="c19" closeto="Mc" which="first">Intersection between c23 and c19</Intersection>
<Line name="l117" n="898" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Midpoint name="M87" n="899" hidden="super" first="Mc" second="P4">Midpoint between Mc and P4</Midpoint>
<Plumb name="p101" n="900" hidden="super" point="M87" line="l117" valid="true">Perpendicular line through M87 to l117</Plumb>
<Intersection name="I111" n="901" hidden="super" first="p101" second="k" which="second">Intersection between p101 and k</Intersection>
<Line name="l118" n="902" hidden="super" from="Mc" to="I111">Line through Mc and I111</Line>
<Midpoint name="M88" n="903" hidden="super" first="Mc" second="I111">Midpoint between Mc and I111</Midpoint>
<Plumb name="p102" n="904" hidden="super" point="M88" line="l118" valid="true">Perpendicular line through M88 to l118</Plumb>
<Intersection name="I112" n="905" hidden="super" first="l117" second="p102">Intersection between l117 and p102</Intersection>
<Line name="l119" n="906" hidden="super" from="P4" to="I110">Line through P4 and I110</Line>
<Midpoint name="M89" n="907" hidden="super" first="P4" second="I110">Midpoint between P4 and I110</Midpoint>
<Plumb name="p103" n="908" hidden="super" point="M89" line="l119" valid="true">Perpendicular line through M89 to l119</Plumb>
<Line name="l120" n="909" hidden="super" from="P4" to="I112">Line through P4 and I112</Line>
<Midpoint name="M90" n="910" hidden="super" first="P4" second="I112">Midpoint between P4 and I112</Midpoint>
<Plumb name="p104" n="911" hidden="super" point="M90" line="l120" valid="true">Perpendicular line through M90 to l120</Plumb>
<Intersection name="I113" n="912" hidden="super" first="p103" second="p104">Intersection between p103 and p104</Intersection>
<Line name="l121" n="913" hidden="super" from="I113" to="I110">Line through I113 and I110</Line>
<Plumb name="p105" n="914" hidden="super" point="I110" line="l121" valid="true">Perpendicular line through I110 to l121</Plumb>
<Line name="l122" n="915" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Intersection name="I114" n="916" hidden="super" first="p105" second="l122">Intersection between p105 and l122</Intersection>
<Circle name="c24" n="917" through="I110" midpoint="I114" acute="true">Circle around I114 through I110</Circle>
<Intersection name="I116" n="937" first="c12" second="c24" shape="circle" which="second">Intersection between c12 and c24</Intersection>
<Line name="l123" n="938" hidden="super" from="Mc" to="P4">Line through Mc and P4</Line>
<Midpoint name="M91" n="939" hidden="super" first="Mc" second="P4">Midpoint between Mc and P4</Midpoint>
<Plumb name="p106" n="940" hidden="super" point="M91" line="l123" valid="true">Perpendicular line through M91 to l123</Plumb>
<Intersection name="I117" n="941" hidden="super" first="p106" second="k" which="second">Intersection between p106 and k</Intersection>
<Line name="l124" n="942" hidden="super" from="Mc" to="I117">Line through Mc and I117</Line>
<Midpoint name="M92" n="943" hidden="super" first="Mc" second="I117">Midpoint between Mc and I117</Midpoint>
<Plumb name="p107" n="944" hidden="super" point="M92" line="l124" valid="true">Perpendicular line through M92 to l124</Plumb>
<Intersection name="I118" n="945" hidden="super" first="l123" second="p107">Intersection between l123 and p107</Intersection>
<Line name="l125" n="946" hidden="super" from="P4" to="I116">Line through P4 and I116</Line>
<Midpoint name="M93" n="947" hidden="super" first="P4" second="I116">Midpoint between P4 and I116</Midpoint>
<Plumb name="p108" n="948" hidden="super" point="M93" line="l125" valid="true">Perpendicular line through M93 to l125</Plumb>
<Line name="l126" n="949" hidden="super" from="P4" to="I118">Line through P4 and I118</Line>
<Midpoint name="M94" n="950" hidden="super" first="P4" second="I118">Midpoint between P4 and I118</Midpoint>
<Plumb name="p109" n="951" hidden="super" point="M94" line="l126" valid="true">Perpendicular line through M94 to l126</Plumb>
<Intersection name="I119" n="952" hidden="super" first="p108" second="p109">Intersection between p108 and p109</Intersection>
<Circle name="c25" n="22" through="P4" midpoint="I119" start="I120" end="I121" acute="true">Circle around I119 through P4</Circle>
<Intersection name="I120" n="954" hidden="true" first="k" second="c25" shape="circle" which="second">Intersection between k and c25</Intersection>
<Intersection name="I121" n="955" hidden="true" first="c25" second="k" shape="circle" which="second">Intersection between c25 and k</Intersection>
</Objects>
</Construction>
</CaR>
